In [35]:
import plotly.express as px

In [5]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("Registration Report.csv", parse_dates=["CREATION DATE", "INSTALLATION DATE"])

# --- Feature Engineering ---
# Calculate TAT (Turnaround Time) in days
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# Categorize SLA buckets
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# Extract month/year for grouping
df["Month"] = df["CREATION DATE"].dt.to_period("M")

# --- Executive Productivity ---
exec_prod = df.groupby(["Sales Executive Name", "Month"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# Yearly totals per executive
exec_year = df.groupby("Sales Executive Name").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Sales Manager Productivity ---
mgr_prod = df.groupby(["Sales Manager", "Month"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

mgr_year = df.groupby("Sales Manager").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Node with Maximum Sales per City ---
node_city = df.groupby(["City", "Installation node"]).agg(
    Customers=("Account no", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby(["Month", "Plan speeds", "Validity"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby(["Month", "SLA_Category"]).agg(
    Customers=("Account no", "count")
).reset_index()

# --- Outlier Analysis ---
outliers = df[df["TAT_days"] > 7]

# --- Save outputs ---
exec_prod.to_csv("executive_monthly.csv", index=False)
exec_year.to_csv("executive_yearly.csv", index=False)
mgr_prod.to_csv("manager_monthly.csv", index=False)
mgr_year.to_csv("manager_yearly.csv", index=False)
node_max.to_csv("node_max_city.csv", index=False)
speed_validity.to_csv("speed_validity_patterns.csv", index=False)
sla_dist.to_csv("sla_distribution.csv", index=False)
outliers.to_csv("tat_outliers.csv", index=False)

print("Analysis complete. CSVs saved.")

C:\Users\Harshal Thakkar\AppData\Local\Temp\ipykernel_15288\2546806860.py:5: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv("Registration Report.csv", parse_dates=["CREATION DATE", "INSTALLATION DATE"])

TypeError: cannot subtract DatetimeArray from ndarray[object]

In [2]:
C:\Users\Harshal\Documents\Broadband\Registration Report.csv

SyntaxError: unexpected character after line continuation character (777690371.py, line 1)

In [3]:
import pandas as pd

file_path = r"C:\Users\Harshal Thakkar\ML Projects\Installation TAT & Sales Performance\Registration Report.csv"
df = pd.read_csv(file_path, parse_dates=["CREATION DATE", "INSTALLATION DATE"])

C:\Users\Harshal Thakkar\AppData\Local\Temp\ipykernel_15288\4257906116.py:4: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv(file_path, parse_dates=["CREATION DATE", "INSTALLATION DATE"])

In [4]:
import os
print(os.getcwd())

C:\Users\Harshal Thakkar

In [6]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("Registration Report.csv", parse_dates=["CREATION DATE", "INSTALLATION DATE"])

# --- Feature Engineering ---
# Calculate TAT (Turnaround Time) in days
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# Categorize SLA buckets
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# Extract month/year for grouping
df["Month"] = df["CREATION DATE"].dt.to_period("M")

# --- Executive Productivity ---
exec_prod = df.groupby(["Sales Executive Name", "Month"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# Yearly totals per executive
exec_year = df.groupby("Sales Executive Name").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Sales Manager Productivity ---
mgr_prod = df.groupby(["Sales Manager", "Month"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

mgr_year = df.groupby("Sales Manager").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Node with Maximum Sales per City ---
node_city = df.groupby(["City", "Installation node"]).agg(
    Customers=("Account no", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby(["Month", "Plan speeds", "Validity"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby(["Month", "SLA_Category"]).agg(
    Customers=("Account no", "count")
).reset_index()

# --- Outlier Analysis ---
outliers = df[df["TAT_days"] > 7]

# --- Save outputs ---
exec_prod.to_csv("executive_monthly.csv", index=False)
exec_year.to_csv("executive_yearly.csv", index=False)
mgr_prod.to_csv("manager_monthly.csv", index=False)
mgr_year.to_csv("manager_yearly.csv", index=False)
node_max.to_csv("node_max_city.csv", index=False)
speed_validity.to_csv("speed_validity_patterns.csv", index=False)
sla_dist.to_csv("sla_distribution.csv", index=False)
outliers.to_csv("tat_outliers.csv", index=False)

print("Analysis complete. CSVs saved.")

C:\Users\Harshal Thakkar\AppData\Local\Temp\ipykernel_15288\2546806860.py:5: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv("Registration Report.csv", parse_dates=["CREATION DATE", "INSTALLATION DATE"])

TypeError: cannot subtract DatetimeArray from ndarray[object]

In [7]:
import pandas as pd

df = pd.read_csv(
    "Registration Report.csv",
    parse_dates=["CREATION DATE", "INSTALLATION DATE"],
    dayfirst=True,  # important for dd-mm-yyyy format
    date_parser=lambda x: pd.to_datetime(x, format="%d-%m-%Y", errors="coerce")
)

TypeError: read_csv() got an unexpected keyword argument 'date_parser'

In [8]:
import pandas as pd

# Step 1: Load raw data
df = pd.read_csv("Registration Report.csv")

# Step 2: Convert date columns explicitly
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Step 3: Calculate TAT
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# Step 4: SLA bucket
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [9]:
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

In [10]:
import pandas as pd

# Step 1: Load raw data
df = pd.read_csv("Registration Report.csv")

# Step 2: Convert date columns explicitly
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Step 3: Calculate TAT
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# Step 4: SLA bucket
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Quick Validation Summary ---
print("\n=== SLA/TAT Sanity Check ===")
print("Total rows:", len(df))
print("Missing dates:", df["TAT_days"].isna().sum())
print("\nOverall TAT stats:")
print(df["TAT_days"].describe())

print("\nMonthly TAT summary:")
monthly_summary = df.groupby(df["CREATION DATE"].dt.to_period("M"))["TAT_days"].agg(["count","min","max","mean"])
print(monthly_summary)

print("\nSLA distribution:")
sla_counts = df["SLA_Category"].value_counts()
print(sla_counts)

=== SLA/TAT Sanity Check ===
Total rows: 14287
Missing dates: 0

Overall TAT stats:
count    14287.000000
mean         3.738154
std          6.292496
min          0.000000
25%          1.000000
50%          2.000000
75%          4.000000
max        196.000000
Name: TAT_days, dtype: float64

Monthly TAT summary:
               count  min  max        mean
CREATION DATE
2025-03            1  114  114  114.000000
2025-04            1   86   86   86.000000
2025-05            3   46   93   69.000000
2025-06          114    1  128   13.403509
2025-07         2192    0  120    3.205292
2025-08         1876    0   88    3.415778
2025-09         1248    0   60    3.281250
2025-10          984    0  180    4.427846
2025-11         1051    0   76    3.493815
2025-12          971    0  196    4.173018
2026-01          848    0   80    4.344340
2026-02          804    0  124    3.779851
2026-03         1051    0   92    3.848716
2026-04         1179    0   65    3.823579
2026-05         1009    0   52    3.522299
2026-06          955    0   28    3.174869

SLA distribution:
SLA_Category
0-2 days        7573
2-5 days        4197
Above 7 days    1402
5-7 days        1115
Name: count, dtype: int64

In [11]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- Calculate TAT ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# --- SLA Buckets ---
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Executive Productivity ---
exec_monthly = df.groupby(["Sales Executive Name", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

exec_yearly = df.groupby("Sales Executive Name").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["Sales Manager", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

mgr_yearly = df.groupby("Sales Manager").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "Installation node"]).agg(
    Customers=("Account no", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby([df["CREATION DATE"].dt.to_period("M"), "Plan speeds", "Validity"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby([df["CREATION DATE"].dt.to_period("M"), "SLA_Category"]).agg(
    Customers=("Account no", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- Print summaries ---
print("\n=== SLA Distribution ===")
print(sla_dist.head(20))

print("\n=== Executive Monthly Productivity ===")
print(exec_monthly.head(20))

print("\n=== Executive Yearly Productivity ===")
print(exec_yearly)

print("\n=== Manager Monthly Productivity ===")
print(mgr_monthly.head(20))

print("\n=== Manager Yearly Productivity ===")
print(mgr_yearly)

print("\n=== Node with Maximum Sales per City ===")
print(node_max)

print("\n=== Speed & Validity Patterns ===")
print(speed_validity.head(20))

print("\n=== Outliers (>7 days) ===")
print(outliers.head(20))

KeyError: 'Sales Executive Name'

In [12]:
print(df.columns.tolist())

['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO', 'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT', 'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value', 'SPEED (Mbps)', 'VALIDITY In Months', 'TAT_days', 'SLA_Category']

In [13]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- Calculate TAT ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# --- SLA Buckets ---
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Executive Productivity ---
exec_monthly = df.groupby(["SALES EXEC NAME", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

exec_yearly = df.groupby("SALES EXEC NAME").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["Sales Manager", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

mgr_yearly = df.groupby("Sales Manager").agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "Installation node"]).agg(
    Customers=("Account no", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby([df["CREATION DATE"].dt.to_period("M"), "Plan speeds", "Validity"]).agg(
    Customers=("Account no", "count"),
    Total_Value=("Plan Value in rupees", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby([df["CREATION DATE"].dt.to_period("M"), "SLA_Category"]).agg(
    Customers=("Account no", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- Print summaries ---
print("\n=== SLA Distribution ===")
print(sla_dist.head(20))

print("\n=== Executive Monthly Productivity ===")
print(exec_monthly.head(20))

print("\n=== Executive Yearly Productivity ===")
print(exec_yearly)

print("\n=== Manager Monthly Productivity ===")
print(mgr_monthly.head(20))

print("\n=== Manager Yearly Productivity ===")
print(mgr_yearly)

print("\n=== Node with Maximum Sales per City ===")
print(node_max)

print("\n=== Speed & Validity Patterns ===")
print(speed_validity.head(20))

print("\n=== Outliers (>7 days) ===")
print(outliers.head(20))

KeyError: "Label(s) ['Account no', 'Plan Value in rupees'] do not exist"

In [14]:
print(df.columns.tolist())

['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO', 'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT', 'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value', 'SPEED (Mbps)', 'VALIDITY In Months', 'TAT_days', 'SLA_Category']

In [15]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- Calculate TAT ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# --- SLA Buckets ---
def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Executive Productivity ---
exec_monthly = df.groupby(["SALES EXEC NAME", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

exec_yearly = df.groupby("SALES EXEC NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["SALES MANGER NAME", df["CREATION DATE"].dt.to_period("M")]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

mgr_yearly = df.groupby("SALES MANGER NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "INSTALLATION NODE"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby([df["CREATION DATE"].dt.to_period("M"), "SPEED (Mbps)", "VALIDITY In Months"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby([df["CREATION DATE"].dt.to_period("M"), "SLA_Category"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- Print summaries ---
print("\n=== SLA Distribution ===")
print(sla_dist.head(20))

print("\n=== Executive Monthly Productivity ===")
print(exec_monthly.head(20))

print("\n=== Executive Yearly Productivity ===")
print(exec_yearly)

print("\n=== Manager Monthly Productivity ===")
print(mgr_monthly.head(20))

print("\n=== Manager Yearly Productivity ===")
print(mgr_yearly)

print("\n=== Node with Maximum Sales per City ===")
print(node_max)

print("\n=== Speed & Validity Patterns ===")
print(speed_validity.head(20))

print("\n=== Outliers (>7 days) ===")
print(outliers.head(20))

=== SLA Distribution ===
   CREATION DATE  SLA_Category  Customers
0        2025-03  Above 7 days          1
1        2025-04  Above 7 days          1
2        2025-05  Above 7 days          3
3        2025-06      0-2 days         11
4        2025-06      2-5 days         34
5        2025-06      5-7 days         12
6        2025-06  Above 7 days         57
7        2025-07      0-2 days       1290
8        2025-07      2-5 days        584
9        2025-07      5-7 days        170
10       2025-07  Above 7 days        148
11       2025-08      0-2 days       1032
12       2025-08      2-5 days        536
13       2025-08      5-7 days        122
14       2025-08  Above 7 days        186
15       2025-09      0-2 days        746
16       2025-09      2-5 days        291
17       2025-09      5-7 days         84
18       2025-09  Above 7 days        127
19       2025-10      0-2 days        511

=== Executive Monthly Productivity ===
            SALES EXEC NAME CREATION DATE  Customers  Total_Value
0             AAKASH KHARVA       2025-07          8        21029
1             AAKASH KHARVA       2025-08          8        21379
2             AAKASH KHARVA       2025-09          7        19514
3             AAKASH KHARVA       2025-10          4         9488
4             AAKASH KHARVA       2025-11          8        21095
5             AAKASH KHARVA       2025-12          8        23530
6             AAKASH KHARVA       2026-01          7        16116
7             AAKASH KHARVA       2026-02          7        16393
8             AAKASH KHARVA       2026-03          9        17448
9             AAKASH KHARVA       2026-04          9        30206
10            AAKASH KHARVA       2026-05          7        13910
11            AAKASH KHARVA       2026-06         10        25904
12            AAKASH MACHHI       2025-07          1         1200
13  AAQIB NOORJAMAL QURESHI       2025-07          1         2542
14  AAQIB NOORJAMAL QURESHI       2025-08          3         2542
15  AAQIB NOORJAMAL QURESHI       2025-09          2         4745
16  AAQIB NOORJAMAL QURESHI       2025-10          1         3050
17  AAQIB NOORJAMAL QURESHI       2026-01          1         1779
18  AAQIB NOORJAMAL QURESHI       2026-03          1         1228
19  AAQIB NOORJAMAL QURESHI       2026-04          1         1779

=== Executive Yearly Productivity ===
              SALES EXEC NAME  Customers  Total_Value
0               AAKASH KHARVA         92       236012
1               AAKASH MACHHI          1         1200
2     AAQIB NOORJAMAL QURESHI         19        31471
3    AAVISHKAR ASHOK SALUNKHE          4        16699
4                ABDUL MULANI         32        89205
..                        ...        ...          ...
781           YOGESH SONAWANE          1         2954
782             YOGESH THAKUR         58       173967
783        YUVRAJSINGH MAHIDA          1         3982
784           Yesha Christian          5            5
785          ZIYAUDDIN SAIYED         52       159432

[786 rows x 3 columns]

=== Manager Monthly Productivity ===
     SALES MANGER NAME CREATION DATE  Customers  Total_Value
0      Animesh Agarwal       2025-06         13        27972
1      Animesh Agarwal       2025-07        124       213422
2      Animesh Agarwal       2025-08        101       187487
3      Animesh Agarwal       2025-09         64       161013
4      Animesh Agarwal       2025-10         56       163141
5      Animesh Agarwal       2025-11         66       188890
6      Animesh Agarwal       2025-12         29        90881
7      Animesh Agarwal       2026-01         16        34899
8      Animesh Agarwal       2026-02         14        32769
9      Animesh Agarwal       2026-03         38        94796
10     Animesh Agarwal       2026-04         33        85147
11     Animesh Agarwal       2026-05         16        41682
12     Animesh Agarwal       2026-06         14        27114
13  DEEPCHANDRA PANDEY       2025-06          2         4465
14  DEEPCHANDRA PANDEY       2025-07         58       147222
15  DEEPCHANDRA PANDEY       2025-08         45       136737
16  DEEPCHANDRA PANDEY       2025-09         35        93663
17  DEEPCHANDRA PANDEY       2025-10         32       112095
18  DEEPCHANDRA PANDEY       2025-11         44       136699
19  DEEPCHANDRA PANDEY       2025-12         34       109538

=== Manager Yearly Productivity ===
      SALES MANGER NAME  Customers  Total_Value
0       Animesh Agarwal        584      1349213
1    DEEPCHANDRA PANDEY        572      1676534
2        HIREN HARIYANI        236       810983
3          IRFAN PATHAN        995      2955626
4      KISHORE NADUPURI        105       250901
5           MAYUR PATEL         40        84725
6   MOHINZMAMUL JAMADAR        529      1439239
7          MOHSIN PATEL       1492      4751765
8         Manish Sarode       1482      4723852
9     RAJBAHADUR SHARMA         92       254024
10        RAJIV BHATIYA       3746     10968375
11    RAMESHREDDY GUDLA        326       927451
12  SANDESH CHANDORIKAR        361      1239288
13   SRINIVAS MALLAVELI       2847      7507901
14       SUSHANT KAJAVE        620      1878381
15        YASHAR PATHAN         82       219844
16        YUSUF HUSSAIN        178       350045

=== Node with Maximum Sales per City ===
               City      INSTALLATION NODE  Customers
40        AHMEDABAD  G-VAIKUN-04-04C01AD39         10
120      AURANGABAD    G-NTWO-04-03C00AB11         20
196       BANGALORE               SW-IND02         21
227         CHENNAI  G-TEMPLE-01-01C01CI12          8
249       HYDERABAD            SW-ADDAGTTA         33
392        KAKINADA              SW-JPGUST         36
431        KHARGHAR             SW-OMSHIVA         13
486          MUMBAI  G-VAKRTUND2-02C01MI11         27
623          NAGPUR  G-SITABULDI-07C01NR04         12
708          NASHIK  G-NEPTUN-06-06C01NK15         17
792     NAVI MUMBAI  G-GREENPRK7-07C01NI03         37
893         NAVSARI            SW-ORNETAPT          7
960           POWAI            SW-ASHOKNGR         11
1239           PUNE             SW-AMANORA        148
1352         RAJKOT  G-GOLDPL-02-01C01RT11         19
1774          SURAT     GOPIPURA-SURCARD04         90
1978          THANE  G-GARDNST11-01C01TE04         11
2237       VADODARA  G-KHTMBA-11-12C01VA52         34
2650         VALSAD            SW-RAJRATNA          3
2684           VAPI            SW-TAPOVAN3          9
2703     VIJAYAWADA            SW-GP1VIJYA          8
3057  VISHAKAPATNAM            SW-TOWNHAL3         24

=== Speed & Validity Patterns ===
   CREATION DATE  SPEED (Mbps)  VALIDITY In Months  Customers  Total_Value
0        2025-03         200.0                12.0          1         9600
1        2025-04          50.0                 3.0          1            1
2        2025-05          25.0                 3.0          1            1
3        2025-05          50.0                12.0          1         5838
4        2025-05         300.0                 6.0          1         3215
5        2025-06           0.0                 3.0          1            1
6        2025-06           3.0                 2.0          1            1
7        2025-06           6.0                 3.0          1            1
8        2025-06          11.0                 3.0          1            1
9        2025-06          20.0                 3.0          1            1
10       2025-06          20.0                 6.0          1         1694
11       2025-06          30.0                 3.0          4         3983
12       2025-06          30.0                 6.0          8        16944
13       2025-06          30.0                12.0         10        35754
14       2025-06          35.0                 3.0          1            1
15       2025-06          40.0                 3.0          7         8400
16       2025-06          40.0                 6.0          8        19198
17       2025-06          40.0                12.0          4        17544
18       2025-06          50.0                 3.0          4         2479
19       2025-06          60.0                 3.0         15        22412

=== Outliers (>7 days) ===
           City CREATION DATE INSTALLATION DATE  ACCOUNT NO CURRENT STATUS  \
17        SURAT    2025-06-23        2025-07-01     2286116         ACTIVE
32        SURAT    2025-06-18        2025-07-01     2286133        SUSPEND
68       NAGPUR    2025-06-21        2025-07-02     2286102         ACTIVE
96   VIJAYAWADA    2025-06-19        2025-07-03     2285040        SUSPEND
107       SURAT    2025-06-23        2025-07-03     2286296        SUSPEND
112       SURAT    2025-06-12        2025-07-03     2286236        SUSPEND
118        PUNE    2025-06-21        2025-07-03     2285530         ACTIVE
122    VADODARA    2025-06-23        2025-07-03     2286305         ACTIVE
175      MUMBAI    2025-06-16        2025-07-04     2286383        SUSPEND
206       SURAT    2025-06-21        2025-07-04     2286404         ACTIVE
213       SURAT    2025-06-23        2025-07-04     2286441        SUSPEND
215      NAGPUR    2025-06-25        2025-07-04     2286429         ACTIVE
232       SURAT    2025-06-23        2025-07-05     2286166        SUSPEND
247      MUMBAI    2025-06-26        2025-07-05     2286490         CLOSED
273       SURAT    2025-06-18        2025-07-05     2286514         ACTIVE
275      NAGPUR    2025-06-16        2025-07-05     2286527        SUSPEND
294       SURAT    2025-06-26        2025-07-05     2286573        SUSPEND
325      NAGPUR    2025-06-25        2025-07-07     2286428         ACTIVE
333   AHMEDABAD    2025-06-28        2025-07-07     2286351        SUSPEND
345      MUMBAI    2025-06-24        2025-07-07     2285273         ACTIVE

               SALES EXEC NAME    SALES MANGER NAME    DEPARTMENT  \
17              DIPAK UPADHYAY        RAJIV BHATIYA  Sales Direct
32                 KARAN PATEL        RAJIV BHATIYA  Sales Direct
68             BHOJRAJ JAWDAND      Animesh Agarwal  Sales Direct
96               DINESH SHINDE   DEEPCHANDRA PANDEY  Sales Direct
107         MUSTANSIR RANGWALA        RAJIV BHATIYA  Sales Direct
112             FOUZAN KAPADIA  MOHINZMAMUL JAMADAR  Sales Direct
118                AMOL JADHAV        Manish Sarode  Sales Direct
122           JAYDEEP KATUDIYA        RAJIV BHATIYA  Sales Direct
175           ARVIND CHAUDHARY        Manish Sarode  Sales Direct
206  MOHAMMEDHUZEFA MORISHWALA         MOHSIN PATEL  Sales Direct
213         MUSTANSIR RANGWALA        RAJIV BHATIYA  Sales Direct
215                MAYUR UIKEY      Animesh Agarwal  Sales Direct
232                 YASH PATEL        RAJIV BHATIYA  Sales Direct
247           ARVIND CHAUDHARY        Manish Sarode  Sales Direct
273                SHANI PATEL        RAJIV BHATIYA  Sales Direct
275            ANKUSH POHANKAR      Animesh Agarwal  Sales Direct
294          RUPESH CHAURASIYA        RAJIV BHATIYA  Sales Direct
325            ANKUSH POHANKAR      Animesh Agarwal  Sales Direct
333      DHARMRAJSINGH CHAUHAN        RAJIV BHATIYA  Sales Direct
345           SWAPNEEL SHASTRI        Manish Sarode   ESG - Sales

         INSTALLATION NODE NETWORK TYPE  \
17    G-MTMKT-D4-04C01ST64         GPON
32    G-SOHAM-01-02C01ST43         GPON
68   G-SUNRAJ-05-05C01NR08         GPON
96             SW-SRELEOFF          MEN
107   G-KRISH-01-04C01ST14         GPON
112       DEMTEX-SURCARD12          HFC
118             SW-AMANORA          MEN
122    G-SAMA-04-4AC04VA12         GPON
175  G-VAKRTUND2-02C01MI11         GPON
206  VASTU SHILP-SURCARD14          HFC
213   G-KRISH-01-04C01ST14         GPON
215   G-AJANI-08-08C01NR15         GPON
232     G-HUB-01-07C01ST50         GPON
247  G-ASHIRWD-4-04C01MI11         GPON
273  G-OMNAGR-01-02C01ST58         GPON
275  G-KDKCLG-06-06C01NR18         GPON
294  G-SARJAN-01-02C01ST37         GPON
325   G-AJANI-03-03C01NR15         GPON
333  G-VAIKUN-04-04C01AD39         GPON
345                    NaN          HFC

                                     REGISTRATION PLAN  Plan Value  \
17   13719/YOU UNLTD 60 Mbps/60Mbps-2Mbps/42TB/12Mo...        4914
32   13726/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...        1652
68   13727/YOU UNLTD 200 Mbps/200Mbps-2Mbps/42TB/12...        7203
96   13720/YOU UNLTD 100 Mbps/100Mbps-2Mbps/21TB/6M...        2965
107  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
112  13914/YOU UNLTD 20 Mbps/20Mbps-2Mbps/21TB/6Mon...        1694
118  13425/YOU UNLTD 300 Mbps/300Mbps-2Mbps/21TB/6M...        4063
122  13718/YOU UNLTD 60 Mbps/60Mbps-2Mbps/21TB/6Mon...        2542
175  13253/YOU PLAY-W 30 Mbps/30Mbps-2Mbps/10.5TB/3...        1681
206  13719/YOU UNLTD 60 Mbps/60Mbps-2Mbps/42TB/12Mo...        4914
213  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
215  12952/YOU UNLTD 100 Mbps/100Mbps-2Mbps/10.5TB/...        1838
232  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
247  12396/YOU UNLTD 30 Mbps/30Mbps-1Mbps/10.5TB/3M...        1200
273  13726/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...        1652
275  13011/YOU UNLTD 40 Mbps/40Mbps-2Mbps/10.5TB/3M...        1200
294  13716/YOU UNLTD 30 Mbps/30Mbps-2Mbps/21TB/6Mon...        2118
325  13703/YOU UNLTD 50 Mbps/50Mbps-2Mbps/10.5TB/3M...         826
333  13709/YOU UNLTD 80 Mbps/80Mbps-2Mbps/10.5TB/3M...         890
345          8324/Leaseline/200Mbps(1:1)/Quarterly/Rs1           1

     SPEED (Mbps)  VALIDITY In Months  TAT_days  SLA_Category
17           60.0                12.0         8  Above 7 days
32           60.0                 3.0        13  Above 7 days
68          200.0                12.0        11  Above 7 days
96          100.0                 6.0        14  Above 7 days
107          30.0                12.0        10  Above 7 days
112          20.0                 6.0        21  Above 7 days
118         300.0                 6.0        12  Above 7 days
122          60.0                 6.0        10  Above 7 days
175          30.0                 3.0        18  Above 7 days
206          60.0                12.0        13  Above 7 days
213          30.0                12.0        11  Above 7 days
215         100.0                 3.0         9  Above 7 days
232          30.0                12.0        12  Above 7 days
247          30.0                 3.0         9  Above 7 days
273          60.0                 3.0        17  Above 7 days
275          40.0                 3.0        19  Above 7 days
294          30.0                 6.0         9  Above 7 days
325          50.0                 3.0        12  Above 7 days
333          80.0                 3.0         9  Above 7 days
345         200.0                 3.0        13  Above 7 days

In [16]:
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

In [17]:
exec_monthly = exec_monthly.sort_values(["Total_Value","Customers"], ascending=False)
mgr_monthly = mgr_monthly.sort_values(["Total_Value","Customers"], ascending=False)
node_max = node_max.sort_values("Customers", ascending=False)
speed_validity = speed_validity.sort_values(["Total_Value","Customers"], ascending=False)

In [18]:
exec_monthly["Total_Value"] = exec_monthly["Total_Value"].round(0)
exec_yearly["Total_Value"] = exec_yearly["Total_Value"].round(0)
mgr_monthly["Total_Value"] = mgr_monthly["Total_Value"].round(0)
mgr_yearly["Total_Value"] = mgr_yearly["Total_Value"].round(0)
speed_validity["Total_Value"] = speed_validity["Total_Value"].round(0)

In [19]:
exec_avg = exec_yearly.copy()
exec_avg["Avg_Customers_per_Month"] = (exec_avg["Customers"] / 12).round(0)
exec_avg["Avg_Value_per_Month"] = (exec_avg["Total_Value"] / 12).round(0)

In [20]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- SLA ageing (Creation → Installation gap) ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Month-Year format for dashboard (Apr-26 style) ---
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- Executive Productivity ---
exec_monthly = df.groupby(["SALES EXEC NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

exec_yearly = df.groupby("SALES EXEC NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["SALES MANGER NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

mgr_yearly = df.groupby("SALES MANGER NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "INSTALLATION NODE"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby(["MonthYear", "SPEED (Mbps)", "VALIDITY In Months"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby(["MonthYear", "SLA_Category"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- Sorting high → low ---
for table in [exec_monthly, exec_yearly, mgr_monthly, mgr_yearly, node_max, speed_validity, sla_dist]:
    if "Total_Value" in table.columns:
        table["Total_Value"] = table["Total_Value"].round(0)
    if "Customers" in table.columns:
        table["Customers"] = table["Customers"].round(0)
    table.sort_values(by=[col for col in ["Total_Value","Customers"] if col in table.columns],

SyntaxError: incomplete input (538447229.py, line 79)

In [21]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- SLA ageing (Creation → Installation gap) ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Month-Year format for dashboard (Apr-26 style) ---
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- Executive Productivity ---
exec_monthly = df.groupby(["SALES EXEC NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

exec_yearly = df.groupby("SALES EXEC NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["SALES MANGER NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

mgr_yearly = df.groupby("SALES MANGER NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "INSTALLATION NODE"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby(["MonthYear", "SPEED (Mbps)", "VALIDITY In Months"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby(["MonthYear", "SLA_Category"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- Rounding and Sorting ---
def clean_table(table):
    if "Total_Value" in table.columns:
        table["Total_Value"] = table["Total_Value"].round(0)
    if "Customers" in table.columns:
        table["Customers"] = table["Customers"].round(0)
    sort_cols = [c for c in ["Total_Value", "Customers"] if c in table.columns]
    if sort_cols:
        table = table.sort_values(by=sort_cols, ascending=False)
    return table

exec_monthly = clean_table(exec_monthly)
exec_yearly = clean_table(exec_yearly)
mgr_monthly = clean_table(mgr_monthly)
mgr_yearly = clean_table(mgr_yearly)
node_max = clean_table(node_max)
speed_validity = clean_table(speed_validity)
sla_dist = clean_table(sla_dist)

# --- Optional: Average productivity per month (yearly ÷ 12) ---
exec_yearly["Avg_Customers_per_Month"] = (exec_yearly["Customers"] / 12).round(0)
exec_yearly["Avg_Value_per_Month"] = (exec_yearly["Total_Value"] / 12).round(0)

mgr_yearly["Avg_Customers_per_Month"] = (mgr_yearly["Customers"] / 12).round(0)
mgr_yearly["Avg_Value_per_Month"] = (mgr_yearly["Total_Value"] / 12).round(0)

# --- Print summaries ---
print("\n=== SLA Distribution ===")
print(sla_dist.head(20))

print("\n=== Executive Monthly Productivity ===")
print(exec_monthly.head(20))

print("\n=== Executive Yearly Productivity (with averages) ===")
print(exec_yearly)

print("\n=== Manager Monthly Productivity ===")
print(mgr_monthly.head(20))

print("\n=== Manager Yearly Productivity (with averages) ===")
print(mgr_yearly)

print("\n=== Node with Maximum Sales per City ===")
print(node_max)

print("\n=== Speed & Validity Patterns ===")
print(speed_validity.head(20))

print("\n=== Outliers (>7 days) ===")
print(outliers.head(20))

=== SLA Distribution ===
   MonthYear SLA_Category  Customers
21    Jul-25     0-2 days       1290
5     Aug-25     0-2 days       1032
51    Sep-25     0-2 days        746
1     Apr-26     0-2 days        594
22    Jul-25     2-5 days        584
43    Nov-25     0-2 days        570
34    Mar-26     0-2 days        540
6     Aug-25     2-5 days        536
39    May-26     0-2 days        522
47    Oct-25     0-2 days        511
29    Jun-26     0-2 days        490
9     Dec-25     0-2 days        458
13    Feb-26     0-2 days        430
17    Jan-26     0-2 days        379
2     Apr-26     2-5 days        358
30    Jun-26     2-5 days        343
40    May-26     2-5 days        333
35    Mar-26     2-5 days        330
44    Nov-25     2-5 days        317
10    Dec-25     2-5 days        304

=== Executive Monthly Productivity ===
          SALES EXEC NAME MonthYear  Customers  Total_Value
1997         Online Sales    Jul-25         50       134954
1993         Online Sales    Aug-25         40       108109
1722  MOHEMADNAZIF SHAIKH    Aug-25         30        94523
2005         Online Sales    Sep-25         30        94336
785          GANESH KANSE    Mar-26         18        93285
2003         Online Sales    Nov-25         30        92052
777          GANESH KANSE    Apr-26         23        90735
1999         Online Sales    Jun-26         31        87820
1994         Online Sales    Dec-25         25        86001
784          GANESH KANSE    Jun-26         21        82712
1747  MOHMMAD ILYAS DHOBI    Jul-25         26        82353
1027     JAGDISH AJMERIYA    Jul-25         21        82131
2002         Online Sales    May-26         21        81359
778          GANESH KANSE    Aug-25         25        79628
789          GANESH KANSE    Sep-25         22        78728
3219       VANDANA RAJPUT    Jul-25         23        78050
787          GANESH KANSE    Nov-25         22        74267
2715        SAMEER HAFEJI    Jul-25         23        73478
985          INAYAT PATEL    Aug-25         22        70462
779          GANESH KANSE    Dec-25         21        70033

=== Executive Yearly Productivity (with averages) ===
         SALES EXEC NAME  Customers  Total_Value  Avg_Customers_per_Month  \
451         Online Sales        312       942692                     26.0
181         GANESH KANSE        237       837540                     20.0
382  MOHEMADNAZIF SHAIKH        218       674828                     18.0
602        SAJEED SAYYAD        174       553977                     14.0
733       VANDANA RAJPUT        158       523743                     13.0
..                   ...        ...          ...                      ...
651   SIDDHARTH DANDEKAR          1            1                      0.0
708         Sunil Thaker          1            1                      0.0
244         JASMIN PATEL          1            0                      0.0
358    MOHAMEDYUSUF SAIT          1            0                      0.0
400        MUKESH JAYPAL          1            0                      0.0

     Avg_Value_per_Month
451              78558.0
181              69795.0
382              56236.0
602              46165.0
733              43645.0
..                   ...
651                  0.0
708                  0.0
244                  0.0
358                  0.0
400                  0.0

[786 rows x 5 columns]

=== Manager Monthly Productivity ===
      SALES MANGER NAME MonthYear  Customers  Total_Value
123       RAJIV BHATIYA    Jul-25        723      1946645
119       RAJIV BHATIYA    Aug-25        572      1532918
163  SRINIVAS MALLAVELI    Jul-25        543      1276840
131       RAJIV BHATIYA    Sep-25        355      1097846
159  SRINIVAS MALLAVELI    Aug-25        450      1019364
129       RAJIV BHATIYA    Nov-25        276       891881
120       RAJIV BHATIYA    Dec-25        275       821238
130       RAJIV BHATIYA    Oct-25        243       807186
170  SRINIVAS MALLAVELI    Oct-25        245       805624
118       RAJIV BHATIYA    Apr-26        270       791436
171  SRINIVAS MALLAVELI    Sep-25        287       761163
97        Manish Sarode    Jul-25        230       660507
125       RAJIV BHATIYA    Jun-26        202       638814
128       RAJIV BHATIYA    May-26        201       615783
127       RAJIV BHATIYA    Mar-26        225       586168
122       RAJIV BHATIYA    Jan-26        197       578604
169  SRINIVAS MALLAVELI    Nov-25        199       568542
93        Manish Sarode    Aug-25        208       559061
121       RAJIV BHATIYA    Feb-26        162       535306
79         MOHSIN PATEL    Aug-25        170       516106

=== Manager Yearly Productivity (with averages) ===
      SALES MANGER NAME  Customers  Total_Value  Avg_Customers_per_Month  \
10        RAJIV BHATIYA       3746     10968375                    312.0
13   SRINIVAS MALLAVELI       2847      7507901                    237.0
7          MOHSIN PATEL       1492      4751765                    124.0
8         Manish Sarode       1482      4723852                    124.0
3          IRFAN PATHAN        995      2955626                     83.0
14       SUSHANT KAJAVE        620      1878381                     52.0
1    DEEPCHANDRA PANDEY        572      1676534                     48.0
6   MOHINZMAMUL JAMADAR        529      1439239                     44.0
0       Animesh Agarwal        584      1349213                     49.0
12  SANDESH CHANDORIKAR        361      1239288                     30.0
11    RAMESHREDDY GUDLA        326       927451                     27.0
2        HIREN HARIYANI        236       810983                     20.0
16        YUSUF HUSSAIN        178       350045                     15.0
9     RAJBAHADUR SHARMA         92       254024                      8.0
4      KISHORE NADUPURI        105       250901                      9.0
15        YASHAR PATHAN         82       219844                      7.0
5           MAYUR PATEL         40        84725                      3.0

    Avg_Value_per_Month
10             914031.0
13             625658.0
7              395980.0
8              393654.0
3              246302.0
14             156532.0
1              139711.0
6              119937.0
0              112434.0
12             103274.0
11              77288.0
2               67582.0
16              29170.0
9               21169.0
4               20908.0
15              18320.0
5                7060.0

=== Node with Maximum Sales per City ===
               City      INSTALLATION NODE  Customers
1239           PUNE             SW-AMANORA        148
1774          SURAT     GOPIPURA-SURCARD04         90
792     NAVI MUMBAI  G-GREENPRK7-07C01NI03         37
392        KAKINADA              SW-JPGUST         36
2237       VADODARA  G-KHTMBA-11-12C01VA52         34
249       HYDERABAD            SW-ADDAGTTA         33
486          MUMBAI  G-VAKRTUND2-02C01MI11         27
3057  VISHAKAPATNAM            SW-TOWNHAL3         24
196       BANGALORE               SW-IND02         21
120      AURANGABAD    G-NTWO-04-03C00AB11         20
1352         RAJKOT  G-GOLDPL-02-01C01RT11         19
708          NASHIK  G-NEPTUN-06-06C01NK15         17
431        KHARGHAR             SW-OMSHIVA         13
623          NAGPUR  G-SITABULDI-07C01NR04         12
1978          THANE  G-GARDNST11-01C01TE04         11
960           POWAI            SW-ASHOKNGR         11
40        AHMEDABAD  G-VAIKUN-04-04C01AD39         10
2684           VAPI            SW-TAPOVAN3          9
227         CHENNAI  G-TEMPLE-01-01C01CI12          8
2703     VIJAYAWADA            SW-GP1VIJYA          8
893         NAVSARI            SW-ORNETAPT          7
2650         VALSAD            SW-RAJRATNA          3

=== Speed & Validity Patterns ===
    MonthYear  SPEED (Mbps)  VALIDITY In Months  Customers  Total_Value
453    Nov-25          40.0                 6.0        203       527754
552    Sep-25          40.0                 6.0        205       513037
242    Jul-25          40.0                 6.0        215       510841
249    Jul-25          60.0                 6.0        190       498902
115    Dec-25          40.0                 6.0        186       476867
362    Mar-26          30.0                12.0        138       475078
240    Jul-25          30.0                12.0        119       451153
502    Oct-25          40.0                 6.0        170       443261
56     Aug-25          40.0                 6.0        182       429244
243    Jul-25          40.0                12.0        102       418004
13     Apr-26          30.0                12.0        122       417744
53     Aug-25          30.0                12.0        105       399334
559    Sep-25          60.0                 6.0        132       373053
57     Aug-25          40.0                12.0         89       372768
250    Jul-25          60.0                12.0         71       357422
258    Jul-25         100.0                 6.0        117       355440
65     Aug-25          60.0                 6.0        133       350859
567    Sep-25         100.0                 6.0        112       348969
460    Nov-25          60.0                 6.0        120       342923
268    Jul-25         200.0                12.0         44       332512

=== Outliers (>7 days) ===
           City CREATION DATE INSTALLATION DATE  ACCOUNT NO CURRENT STATUS  \
17        SURAT    2025-06-23        2025-07-01     2286116         ACTIVE
32        SURAT    2025-06-18        2025-07-01     2286133        SUSPEND
68       NAGPUR    2025-06-21        2025-07-02     2286102         ACTIVE
96   VIJAYAWADA    2025-06-19        2025-07-03     2285040        SUSPEND
107       SURAT    2025-06-23        2025-07-03     2286296        SUSPEND
112       SURAT    2025-06-12        2025-07-03     2286236        SUSPEND
118        PUNE    2025-06-21        2025-07-03     2285530         ACTIVE
122    VADODARA    2025-06-23        2025-07-03     2286305         ACTIVE
175      MUMBAI    2025-06-16        2025-07-04     2286383        SUSPEND
206       SURAT    2025-06-21        2025-07-04     2286404         ACTIVE
213       SURAT    2025-06-23        2025-07-04     2286441        SUSPEND
215      NAGPUR    2025-06-25        2025-07-04     2286429         ACTIVE
232       SURAT    2025-06-23        2025-07-05     2286166        SUSPEND
247      MUMBAI    2025-06-26        2025-07-05     2286490         CLOSED
273       SURAT    2025-06-18        2025-07-05     2286514         ACTIVE
275      NAGPUR    2025-06-16        2025-07-05     2286527        SUSPEND
294       SURAT    2025-06-26        2025-07-05     2286573        SUSPEND
325      NAGPUR    2025-06-25        2025-07-07     2286428         ACTIVE
333   AHMEDABAD    2025-06-28        2025-07-07     2286351        SUSPEND
345      MUMBAI    2025-06-24        2025-07-07     2285273         ACTIVE

               SALES EXEC NAME    SALES MANGER NAME    DEPARTMENT  \
17              DIPAK UPADHYAY        RAJIV BHATIYA  Sales Direct
32                 KARAN PATEL        RAJIV BHATIYA  Sales Direct
68             BHOJRAJ JAWDAND      Animesh Agarwal  Sales Direct
96               DINESH SHINDE   DEEPCHANDRA PANDEY  Sales Direct
107         MUSTANSIR RANGWALA        RAJIV BHATIYA  Sales Direct
112             FOUZAN KAPADIA  MOHINZMAMUL JAMADAR  Sales Direct
118                AMOL JADHAV        Manish Sarode  Sales Direct
122           JAYDEEP KATUDIYA        RAJIV BHATIYA  Sales Direct
175           ARVIND CHAUDHARY        Manish Sarode  Sales Direct
206  MOHAMMEDHUZEFA MORISHWALA         MOHSIN PATEL  Sales Direct
213         MUSTANSIR RANGWALA        RAJIV BHATIYA  Sales Direct
215                MAYUR UIKEY      Animesh Agarwal  Sales Direct
232                 YASH PATEL        RAJIV BHATIYA  Sales Direct
247           ARVIND CHAUDHARY        Manish Sarode  Sales Direct
273                SHANI PATEL        RAJIV BHATIYA  Sales Direct
275            ANKUSH POHANKAR      Animesh Agarwal  Sales Direct
294          RUPESH CHAURASIYA        RAJIV BHATIYA  Sales Direct
325            ANKUSH POHANKAR      Animesh Agarwal  Sales Direct
333      DHARMRAJSINGH CHAUHAN        RAJIV BHATIYA  Sales Direct
345           SWAPNEEL SHASTRI        Manish Sarode   ESG - Sales

         INSTALLATION NODE NETWORK TYPE  \
17    G-MTMKT-D4-04C01ST64         GPON
32    G-SOHAM-01-02C01ST43         GPON
68   G-SUNRAJ-05-05C01NR08         GPON
96             SW-SRELEOFF          MEN
107   G-KRISH-01-04C01ST14         GPON
112       DEMTEX-SURCARD12          HFC
118             SW-AMANORA          MEN
122    G-SAMA-04-4AC04VA12         GPON
175  G-VAKRTUND2-02C01MI11         GPON
206  VASTU SHILP-SURCARD14          HFC
213   G-KRISH-01-04C01ST14         GPON
215   G-AJANI-08-08C01NR15         GPON
232     G-HUB-01-07C01ST50         GPON
247  G-ASHIRWD-4-04C01MI11         GPON
273  G-OMNAGR-01-02C01ST58         GPON
275  G-KDKCLG-06-06C01NR18         GPON
294  G-SARJAN-01-02C01ST37         GPON
325   G-AJANI-03-03C01NR15         GPON
333  G-VAIKUN-04-04C01AD39         GPON
345                    NaN          HFC

                                     REGISTRATION PLAN  Plan Value  \
17   13719/YOU UNLTD 60 Mbps/60Mbps-2Mbps/42TB/12Mo...        4914
32   13726/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...        1652
68   13727/YOU UNLTD 200 Mbps/200Mbps-2Mbps/42TB/12...        7203
96   13720/YOU UNLTD 100 Mbps/100Mbps-2Mbps/21TB/6M...        2965
107  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
112  13914/YOU UNLTD 20 Mbps/20Mbps-2Mbps/21TB/6Mon...        1694
118  13425/YOU UNLTD 300 Mbps/300Mbps-2Mbps/21TB/6M...        4063
122  13718/YOU UNLTD 60 Mbps/60Mbps-2Mbps/21TB/6Mon...        2542
175  13253/YOU PLAY-W 30 Mbps/30Mbps-2Mbps/10.5TB/3...        1681
206  13719/YOU UNLTD 60 Mbps/60Mbps-2Mbps/42TB/12Mo...        4914
213  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
215  12952/YOU UNLTD 100 Mbps/100Mbps-2Mbps/10.5TB/...        1838
232  13717/YOU UNLTD 30 Mbps/30Mbps-2Mbps/42TB/12Mo...        3728
247  12396/YOU UNLTD 30 Mbps/30Mbps-1Mbps/10.5TB/3M...        1200
273  13726/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...        1652
275  13011/YOU UNLTD 40 Mbps/40Mbps-2Mbps/10.5TB/3M...        1200
294  13716/YOU UNLTD 30 Mbps/30Mbps-2Mbps/21TB/6Mon...        2118
325  13703/YOU UNLTD 50 Mbps/50Mbps-2Mbps/10.5TB/3M...         826
333  13709/YOU UNLTD 80 Mbps/80Mbps-2Mbps/10.5TB/3M...         890
345          8324/Leaseline/200Mbps(1:1)/Quarterly/Rs1           1

     SPEED (Mbps)  VALIDITY In Months  TAT_days  SLA_Category MonthYear
17           60.0                12.0         8  Above 7 days    Jun-25
32           60.0                 3.0        13  Above 7 days    Jun-25
68          200.0                12.0        11  Above 7 days    Jun-25
96          100.0                 6.0        14  Above 7 days    Jun-25
107          30.0                12.0        10  Above 7 days    Jun-25
112          20.0                 6.0        21  Above 7 days    Jun-25
118         300.0                 6.0        12  Above 7 days    Jun-25
122          60.0                 6.0        10  Above 7 days    Jun-25
175          30.0                 3.0        18  Above 7 days    Jun-25
206          60.0                12.0        13  Above 7 days    Jun-25
213          30.0                12.0        11  Above 7 days    Jun-25
215         100.0                 3.0         9  Above 7 days    Jun-25
232          30.0                12.0        12  Above 7 days    Jun-25
247          30.0                 3.0         9  Above 7 days    Jun-25
273          60.0                 3.0        17  Above 7 days    Jun-25
275          40.0                 3.0        19  Above 7 days    Jun-25
294          30.0                 6.0         9  Above 7 days    Jun-25
325          50.0                 3.0        12  Above 7 days    Jun-25
333          80.0                 3.0         9  Above 7 days    Jun-25
345         200.0                 3.0        13  Above 7 days    Jun-25

In [22]:
print(exec_monthly.to_string(index=False))

                             SALES EXEC NAME MonthYear  Customers  Total_Value
                                Online Sales    Jul-25         50       134954
                                Online Sales    Aug-25         40       108109
                         MOHEMADNAZIF SHAIKH    Aug-25         30        94523
                                Online Sales    Sep-25         30        94336
                                GANESH KANSE    Mar-26         18        93285
                                Online Sales    Nov-25         30        92052
                                GANESH KANSE    Apr-26         23        90735
                                Online Sales    Jun-26         31        87820
                                Online Sales    Dec-25         25        86001
                                GANESH KANSE    Jun-26         21        82712
                         MOHMMAD ILYAS DHOBI    Jul-25         26        82353
                            JAGDISH AJMERIYA    Jul-25         21        82131
                                Online Sales    May-26         21        81359
                                GANESH KANSE    Aug-25         25        79628
                                GANESH KANSE    Sep-25         22        78728
                              VANDANA RAJPUT    Jul-25         23        78050
                                GANESH KANSE    Nov-25         22        74267
                               SAMEER HAFEJI    Jul-25         23        73478
                                INAYAT PATEL    Aug-25         22        70462
                                GANESH KANSE    Dec-25         21        70033
                             JANAKBEN PARMAR    Jul-25         22        69986
                         MOHEMADNAZIF SHAIKH    Jun-26         21        67190
                                Online Sales    Apr-26         23        66792
                            JAGDISH AJMERIYA    Oct-25         15        65156
                             JANAKBEN PARMAR    Nov-25         15        63819
                              SUSHANT REMAJE    Jul-25         18        63780
                         MOHEMADNAZIF SHAIKH    Feb-26         20        63661
                                  HIREN MODI    Feb-26          1        62991
                         MOHEMADNAZIF SHAIKH    Apr-26         21        62732
                                GANESH KANSE    Jan-26         16        62528
                      MOHAMMEDHANEEF PATIDAR    Aug-25         18        61942
                               SAJEED SAYYAD    Aug-25         19        61762
                               SAJEED SAYYAD    Oct-25         15        60918
                              VANDANA RAJPUT    Apr-26         15        60621
                                GANESH KANSE    Jul-25         22        60152
                               SAJEED SAYYAD    Jul-25         20        59757
                            JAGDISH AJMERIYA    Nov-25         13        59480
                      MOHAMMEDHANEEF PATIDAR    Jul-25         20        59138
                               SAMEER HAFEJI    Aug-25         16        59042
                                INAYAT PATEL    Jul-25         16        58352
                                Online Sales    Jan-26         19        58277
                             JANAKBEN PARMAR    May-26         16        57432
                         MOHEMADNAZIF SHAIKH    Nov-25         16        57101
                              SUSHANT REMAJE    Apr-26         15        56917
                                JIMIT MACHHI    Jul-25         26        56051
                             RAMNARESH YADAV    Jul-25         21        55712
                   MOHAMMEDHUZEFA MORISHWALA    Mar-26         14        55368
                              VANDANA RAJPUT    Aug-25         22        55292
                         MOHEMADNAZIF SHAIKH    Jan-26         17        55254
                               SAJEED SAYYAD    Sep-25         14        54712
                               IRFAN HANSLOD    Jul-25         11        54653
                                INAYAT PATEL    Feb-26         16        54605
                         MOHEMADNAZIF SHAIKH    Jul-25         21        54503
                          NIMISHABAHEN PATEL    Aug-25         19        54488
                            JAGDISH AJMERIYA    Jun-26         14        54276
                                      VENU G    Jul-25         15        54246
                             JANAKBEN PARMAR    Aug-25         16        53634
                             RAMESH SANGEKAR    Jun-26         12        53368
                      MOHAMMEDHANEEF PATIDAR    May-26         12        53160
                   MOHAMMEDHUZEFA MORISHWALA    Aug-25         16        53094
                                 SURAJ KHODE    Feb-26         18        52575
                              SUSHANT REMAJE    Jun-26         18        52440
                        MOHAMMADSUFEL SHAIKH    Aug-25         22        52267
                               PRAVEEN SAROJ    Jan-26          4        52224
                   MOHAMMEDHUZEFA MORISHWALA    Jul-25         15        51860
                                Online Sales    Mar-26         16        51716
                          NIMISHABAHEN PATEL    Jul-25         12        51668
                           MOHAMMAD MOTIWALA    Mar-26         14        50872
                         MOHEMADNAZIF SHAIKH    Dec-25         15        50746
                         RAVINDERREDDY MUSKU    Oct-25         14        50578
                               WALK INN PUNE    Oct-25          9        50191
                                INAYAT PATEL    Mar-26         18        50069
                                  AMOL AARTE    Aug-25          9        48673
                                GANESH KANSE    May-26         19        48122
                                GANESH KANSE    Oct-25         13        48093
                              SUSHANT REMAJE    Oct-25          9        47928
                               SAJEED SAYYAD    Nov-25         13        47753
                           PRINCEKUMAR PATEL    Jul-25         16        47661
                             RAMESH SANGEKAR    Mar-26         13        47640
                               SAJEED SAYYAD    Mar-26         18        47502
                                INAYAT PATEL    Oct-25         15        47177
                             JANAKBEN PARMAR    Apr-26         14        47080
                         NASEEM AHMED SHAIKH    Jan-26          6        47048
                               IRFAN HANSLOD    May-26         12        46897
                            JAGDISH AJMERIYA    Apr-26         15        46764
                              SUSHANT REMAJE    Nov-25         11        46726
                             MD ZAFAR EQUBAL    Jul-25          8        46314
                             JANAKBEN PARMAR    Jun-26         14        46214
                           MOHAMMAD MOTIWALA    Jul-25         16        46171
                                ROHIT SHETTY    Nov-25         14        46049
                         MOHEMADNAZIF SHAIKH    Mar-26         15        46016
                                FARIZ LALANI    Sep-25         17        46013
                                ROHIT SHETTY    Oct-25         13        45938
                                GANESH KANSE    Feb-26         13        45471
                                ALMAS SHAIKH    Jul-25         13        45434
                                    VIKRAM R    Jul-25         16        45433
                                 AMOL JADHAV    Aug-25         10        45299
                             JANAKBEN PARMAR    Jan-26          9        45262
                             RAMESH SANGEKAR    Jul-25         15        44799
                              BHUMIKA PARMAR    Oct-25          9        44737
                              KISHAN SOLANKI    Nov-25         13        44686
                 KOLLI VENKATA NAGESWARA RAO    Apr-26         17        44602
                          SALAPU HARIKRISHNA    Jul-25         18        44525
                             RAMESH SANGEKAR    Apr-26         17        44390
                             RAMESH SANGEKAR    Sep-25         13        44010
                               IRFAN HANSLOD    Feb-26         11        43801
                            JAGDISH AJMERIYA    Sep-25         15        43796
                         MOHEMADNAZIF SHAIKH    Oct-25         13        43475
                         ABHILASH GOLLAPALLI    Jul-25         16        43429
                                    VIKRAM R    Oct-25         12        43376
                                Online Sales    Feb-26         14        43017
                          NIMISHABAHEN PATEL    Feb-26         13        42700
                              AVINASH SHEGAR    Jul-25         12        42678
                              MOAKRAM SHAIKH    Nov-25         12        42616
                                 SURAJ KHODE    Dec-25         11        42588
                                PRATIK PATEL    Dec-25          9        42577
                                IMRAN SHAIKH    Aug-25         15        42534
                              ANIL GANGARKAR    Nov-25         10        42486
                                    VIKRAM R    Aug-25         14        42376
                              VANDANA RAJPUT    Dec-25         14        42369
                               SAJEED SAYYAD    Jan-26         16        42173
                             MOHASHIN SHAIKH    Mar-26         12        42153
                              AMOL NAIKNAWRE    Oct-25         13        42139
                 KOLLI VENKATA NAGESWARA RAO    Jun-26         17        42102
                              SUSHANT REMAJE    Feb-26         12        41995
                               MUKESH NAGARE    Nov-25         11        41952
                             RAMESH SANGEKAR    May-26         15        41832
                      MOHAMMEDHANEEF PATIDAR    Feb-26         14        41768
                                 AMAR JACHAK    Jul-25         15        41506
                              ANIL GANGARKAR    Jan-26         10        41504
                           NILESH KHANDAGALE    Jul-25         10        41464
                           MOHAMMAD MOTIWALA    Aug-25         14        41380
                                INAYAT PATEL    May-26         11        41177
                               SAMEER HAFEJI    Mar-26         11        41177
                               BIDHAN MANDAL    Jul-25         13        41159
                              AVINASH SHEGAR    Aug-25         11        41075
                               SAJEED SAYYAD    May-26         14        41016
                    SATEESHREDDY JAGANNADHAM    Aug-25         19        40835
                         JAYLESHKUMAR PARMAR    Jul-25         12        40706
                              BHUMIKA PARMAR    Nov-25          8        40694
                         JAYLESHKUMAR PARMAR    Nov-25         11        40670
                               SAMEER HAFEJI    Nov-25         11        40583
                                JIMIT MACHHI    Mar-26         14        40467
                         NASEEM AHMED SHAIKH    Oct-25          5        40259
                               IRFAN HANSLOD    Jun-26         11        40245
                           MOHAMMAD MOTIWALA    Apr-26         14        40236
                               DINESH SHINDE    Oct-25          9        39943
                               SAMEER HAFEJI    Jun-26         10        39780
                        MOHAMMADSUFEL SHAIKH    Apr-26         10        39563
                                ROHIT SHETTY    Aug-25         12        39487
                             RAMNARESH YADAV    Aug-25         14        39478
                                  VICKY SHAH    Dec-25          9        39475
                               IRFAN HANSLOD    Jan-26         11        39354
                               SAJEED SAYYAD    Dec-25          9        39324
                                 AMAR JACHAK    Jan-26          9        39254
                             RAMNARESH YADAV    Nov-25         13        39057
                      KARAN UMESHSINGHRAJPUT    Sep-25         10        38900
                               SAJEED SAYYAD    Apr-26         14        38801
                             KEYUR GHADIYALI    Jan-26         12        38719
                              VANDANA RAJPUT    Mar-26         13        38687
                   MOHAMMEDHUZEFA MORISHWALA    Feb-26         14        38674
                              SUSHANT REMAJE    Aug-25         17        38646
                               IRFAN HANSLOD    Dec-25         12        38632
                              ANIL GANGARKAR    Jul-25         18        38574
                              ANIL GANGARKAR    May-26          9        38515
                            JAYDEEP KATUDIYA    Jul-25         17        38412
                 KOLLI VENKATA NAGESWARA RAO    Nov-25         13        38367
                                MAHESH PATEL    Nov-25         13        38329
                        MOHAMMADSUFEL SHAIKH    Nov-25         12        38210
                            JAGDISH AJMERIYA    Aug-25         11        37986
                                 SURAJ KHODE    Jan-26         12        37982
                            JAYDEEP KATUDIYA    Mar-26         14        37866
                              MOAKRAM SHAIKH    Feb-26         10        37787
                           RUPESH CHAURASIYA    Oct-25         10        37781
                                  VICKY SHAH    Jan-26         10        37703
                               RAVI VADOLIYA    Jul-25         11        37656
                              SUSHANT REMAJE    Jan-26         13        37647
                      MOHAMMEDHANEEF PATIDAR    Dec-25         10        37618
                               IRFAN HANSLOD    Aug-25         11        37534
                                  VICKY SHAH    Feb-26          8        37442
                              VANDANA RAJPUT    Jun-26         10        37303
                                   RAJ GUPTA    Jun-26          8        37103
                             JANAKBEN PARMAR    Dec-25         11        37024
                             JANAKBEN PARMAR    Oct-25          9        36983
                                      VENU G    Oct-25         10        36975
                         NASEEM AHMED SHAIKH    Jun-26          8        36943
                             RUCHITA KANSARA    Aug-25         10        36936
                              VANDANA RAJPUT    Jan-26         12        36767
                            JAYDEEP KATUDIYA    Jun-26          8        36724
                                JIMIT MACHHI    Apr-26         10        36715
                         MOHEMADNAZIF SHAIKH    May-26         15        36670
                           LAKSHMANARAO AVVA    Dec-25         14        36614
                             RAMNARESH YADAV    Oct-25         10        36611
                      MOHAMMEDHANEEF PATIDAR    Nov-25         11        36539
                              KAUSHIK VANKAR    Apr-26         12        36530
                              ANIL GANGARKAR    Dec-25         11        36522
                               YOGESH THAKUR    Oct-25          9        36417
                           SRINIVASRAO KOLLI    Jul-25         14        36387
                              BHUMIKA PARMAR    Apr-26         11        36232
                          NIMISHABAHEN PATEL    Nov-25          9        36202
                              AVINASH SHEGAR    Jun-26         12        36157
                            AFZALKHAN PATHAN    May-26         12        36134
                              BHUMIKA PARMAR    Dec-25          8        36134
                             SALMAN SABUVALA    Nov-25         10        36092
                             RAMNARESH YADAV    Dec-25         13        36043
                   MOHAMMEDHUZEFA MORISHWALA    Jan-26         11        36006
                               WALK INN PUNE    Sep-25          5        35952
                                  FARUQ SONI    Jun-26         11        35876
                               TAIYAB SHAIKH    Jul-25         11        35712
                           VIKASKUMAR SHARMA    Nov-25         10        35710
                              VANDANA RAJPUT    Oct-25          9        35669
                             GANTYADA NANAJI    Jun-26         10        35580
                               TAIYAB SHAIKH    May-26         11        35457
                              SUSHANT REMAJE    Dec-25         11        35394
                            AZAZAHMED NAGORI    May-26         12        35305
                                KALPESH MALI    Oct-25          8        35205
                               RAVI VADOLIYA    Sep-25          9        35076
                                KALPESH MALI    May-26          8        34926
                             MOHASHIN SHAIKH    Apr-26         11        34788
                              SUSHANT REMAJE    Sep-25         15        34706
                        ABDULFAIZAL RAJBHARA    Jan-26         11        34675
                              AVINASH SHEGAR    Apr-26         11        34655
                                INAYAT PATEL    Nov-25          8        34569
                               TAIYAB SHAIKH    Aug-25         10        34552
                          SALAPU HARIKRISHNA    Jun-26         10        34551
                             SALMAN SABUVALA    Apr-26         10        34338
                      MOHAMMEDHANEEF PATIDAR    Jan-26         11        34310
                              MOAKRAM SHAIKH    Aug-25         10        34240
                                ROHIT SHETTY    Sep-25         11        34163
                            KIRANKUMAR PAKKI    Nov-25          9        34153
                              BHUMIKA PARMAR    Jul-25         11        34066
                         MOHEMADNAZIF SHAIKH    Sep-25         10        34061
                             RAMESH SANGEKAR    Dec-25         12        33986
                                  YASH PATEL    Jul-25         12        33926
                                ALMAS SHAIKH    Aug-25         10        33915
                                GAYTRI YADAV    Oct-25          9        33893
                                 SURAJ KHODE    Sep-25         11        33789
                                 SURAJ KHODE    Jun-26         12        33785
                   MOHAMMEDHUZEFA MORISHWALA    Nov-25          9        33721
                             MOHASHIN SHAIKH    Jun-26         11        33658
                               MUKESH NAGARE    Sep-25          9        33577
                                ADARSH NAGAR    Jul-25         14        33537
                               SAJEED SAYYAD    Feb-26         14        33523
                                IMRAN SHAIKH    Oct-25         11        33321
                              KISHAN SOLANKI    Oct-25          7        33302
                               DINESH SHINDE    Jan-26          8        33215
                           MOHAMMAD MOTIWALA    Nov-25          9        33212
                            ZIYAUDDIN SAIYED    May-26          9        33205
                                 SURAJ KHODE    Jul-25         11        33198
                               IRFAN HANSLOD    Nov-25         10        33127
                           VIKASKUMAR SHARMA    Dec-25          9        33082
                        MOHAMMADSUFEL SHAIKH    Jul-25         11        33043

In [23]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- SLA ageing (Creation → Installation gap) ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Month-Year format for dashboard (Apr-26 style) ---
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- Executive Productivity ---
exec_monthly = df.groupby(["SALES EXEC NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

exec_yearly = df.groupby("SALES EXEC NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Manager Productivity ---
mgr_monthly = df.groupby(["SALES MANGER NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

mgr_yearly = df.groupby("SALES MANGER NAME").agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Node Analysis (Top node per city) ---
node_city = df.groupby(["City", "INSTALLATION NODE"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

node_max = node_city.loc[node_city.groupby("City")["Customers"].idxmax()]

# --- Speed & Validity Patterns ---
speed_validity = df.groupby(["MonthYear", "SPEED (Mbps)", "VALIDITY In Months"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- SLA Distribution ---
sla_dist = df.groupby(["MonthYear", "SLA_Category"]).agg(
    Customers=("ACCOUNT NO", "count")
).reset_index()

# --- Outliers (>7 days) ---
outliers = df[df["TAT_days"] > 7]

# --- City-Level Analysis ---
city_monthly = df.groupby(["City", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Plan-Level Analysis ---
plan_monthly = df.groupby(["REGISTRATION PLAN", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Executive Selling Pattern by Speed/Validity/Plan Value ---
exec_speed_validity = df.groupby(["SALES EXEC NAME", "SPEED (Mbps)", "VALIDITY In Months"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Rounding and Sorting ---
def clean_table(table):
    if "Total_Value" in table.columns:
        table["Total_Value"] = table["Total_Value"].round(0)
    if "Customers" in table.columns:
        table["Customers"] = table["Customers"].round(0)
    sort_cols = [c for c in ["Total_Value", "Customers"] if c in table.columns]
    if sort_cols:
        table = table.sort_values(by=sort_cols, ascending=False)
    return table.reset_index(drop=True)  # remove row indices

exec_monthly = clean_table(exec_monthly)
exec_yearly = clean_table(exec_yearly)
mgr_monthly = clean_table(mgr_monthly)
mgr_yearly = clean_table(mgr_yearly)
node_max = clean_table(node_max)
speed_validity = clean_table(speed_validity)
sla_dist = clean_table(sla_dist)
city_monthly = clean_table(city_monthly)
plan_monthly = clean_table(plan_monthly)
exec_speed_validity = clean_table(exec_speed_validity)

# --- Optional: Average productivity per month (yearly ÷ 12) ---
exec_yearly["Avg_Customers_per_Month"] = (exec_yearly["Customers"] / 12).round(0)
exec_yearly["Avg_Value_per_Month"] = (exec_yearly["Total_Value"] / 12).round(0)

mgr_yearly["Avg_Customers_per_Month"] = (mgr_yearly["Customers"] / 12).round(0)
mgr_yearly["Avg_Value_per_Month"] = (mgr_yearly["Total_Value"] / 12).round(0)

# --- Print summaries without indices ---
print("\n=== SLA Distribution ===")
print(sla_dist.to_string(index=False))

print("\n=== Executive Monthly Productivity ===")
print(exec_monthly.to_string(index=False))

print("\n=== Executive Yearly Productivity (with averages) ===")
print(exec_yearly.to_string(index=False))

print("\n=== Manager Monthly Productivity ===")
print(mgr_monthly.to_string(index=False))

print("\n=== Manager Yearly Productivity (with averages) ===")
print(mgr_yearly.to_string(index=False))

print("\n=== Node with Maximum Sales per City ===")
print(node_max.to_string(index=False))

print("\n=== Speed & Validity Patterns ===")
print(speed_validity.to_string(index=False))

print("\n=== City-Level Monthly Productivity ===")
print(city_monthly.to_string(index=False))

print("\n=== Plan-Level Monthly Productivity ===")
print(plan_monthly.to_string(index=False))

print("\n=== Executive Selling Pattern by Speed/Validity ===")
print(exec_speed_validity.to_string(index=False))

print("\n=== Outliers (>7 days) ===")
print(outliers.to_string(index=False))

=== SLA Distribution ===
MonthYear SLA_Category  Customers
   Jul-25     0-2 days       1290
   Aug-25     0-2 days       1032
   Sep-25     0-2 days        746
   Apr-26     0-2 days        594
   Jul-25     2-5 days        584
   Nov-25     0-2 days        570
   Mar-26     0-2 days        540
   Aug-25     2-5 days        536
   May-26     0-2 days        522
   Oct-25     0-2 days        511
   Jun-26     0-2 days        490
   Dec-25     0-2 days        458
   Feb-26     0-2 days        430
   Jan-26     0-2 days        379
   Apr-26     2-5 days        358
   Jun-26     2-5 days        343
   May-26     2-5 days        333
   Mar-26     2-5 days        330
   Nov-25     2-5 days        317
   Dec-25     2-5 days        304
   Sep-25     2-5 days        291
   Jan-26     2-5 days        277
   Oct-25     2-5 days        248
   Feb-26     2-5 days        242
   Aug-25 Above 7 days        186
   Jul-25     5-7 days        170
   Oct-25 Above 7 days        151
   Jul-25 Above 7 days        148
   Sep-25 Above 7 days        127
   Aug-25     5-7 days        122
   Apr-26     5-7 days        120
   Dec-25 Above 7 days        114
   Jan-26 Above 7 days        112
   Apr-26 Above 7 days        107
   Mar-26 Above 7 days        100
   Dec-25     5-7 days         95
   Sep-25     5-7 days         84
   May-26 Above 7 days         84
   Nov-25     5-7 days         82
   Nov-25 Above 7 days         82
   Mar-26     5-7 days         81
   Jan-26     5-7 days         80
   Feb-26 Above 7 days         74
   Oct-25     5-7 days         74
   May-26     5-7 days         70
   Jun-26     5-7 days         67
   Feb-26     5-7 days         58
   Jun-25 Above 7 days         57
   Jun-26 Above 7 days         55
   Jun-25     2-5 days         34
   Jun-25     5-7 days         12
   Jun-25     0-2 days         11
   May-25 Above 7 days          3
   Apr-25 Above 7 days          1
   Mar-25 Above 7 days          1

=== Executive Monthly Productivity ===
                             SALES EXEC NAME MonthYear  Customers  Total_Value
                                Online Sales    Jul-25         50       134954
                                Online Sales    Aug-25         40       108109
                         MOHEMADNAZIF SHAIKH    Aug-25         30        94523
                                Online Sales    Sep-25         30        94336
                                GANESH KANSE    Mar-26         18        93285
                                Online Sales    Nov-25         30        92052
                                GANESH KANSE    Apr-26         23        90735
                                Online Sales    Jun-26         31        87820
                                Online Sales    Dec-25         25        86001
                                GANESH KANSE    Jun-26         21        82712
                         MOHMMAD ILYAS DHOBI    Jul-25         26        82353
                            JAGDISH AJMERIYA    Jul-25         21        82131
                                Online Sales    May-26         21        81359
                                GANESH KANSE    Aug-25         25        79628
                                GANESH KANSE    Sep-25         22        78728
                              VANDANA RAJPUT    Jul-25         23        78050
                                GANESH KANSE    Nov-25         22        74267
                               SAMEER HAFEJI    Jul-25         23        73478
                                INAYAT PATEL    Aug-25         22        70462
                                GANESH KANSE    Dec-25         21        70033
                             JANAKBEN PARMAR    Jul-25         22        69986
                         MOHEMADNAZIF SHAIKH    Jun-26         21        67190
                                Online Sales    Apr-26         23        66792
                            JAGDISH AJMERIYA    Oct-25         15        65156
                             JANAKBEN PARMAR    Nov-25         15        63819
                              SUSHANT REMAJE    Jul-25         18        63780
                         MOHEMADNAZIF SHAIKH    Feb-26         20        63661
                                  HIREN MODI    Feb-26          1        62991
                         MOHEMADNAZIF SHAIKH    Apr-26         21        62732
                                GANESH KANSE    Jan-26         16        62528
                      MOHAMMEDHANEEF PATIDAR    Aug-25         18        61942
                               SAJEED SAYYAD    Aug-25         19        61762
                               SAJEED SAYYAD    Oct-25         15        60918
                              VANDANA RAJPUT    Apr-26         15        60621
                                GANESH KANSE    Jul-25         22        60152
                               SAJEED SAYYAD    Jul-25         20        59757
                            JAGDISH AJMERIYA    Nov-25         13        59480
                      MOHAMMEDHANEEF PATIDAR    Jul-25         20        59138
                               SAMEER HAFEJI    Aug-25         16        59042
                                INAYAT PATEL    Jul-25         16        58352
                                Online Sales    Jan-26         19        58277
                             JANAKBEN PARMAR    May-26         16        57432
                         MOHEMADNAZIF SHAIKH    Nov-25         16        57101
                              SUSHANT REMAJE    Apr-26         15        56917
                                JIMIT MACHHI    Jul-25         26        56051
                             RAMNARESH YADAV    Jul-25         21        55712
                   MOHAMMEDHUZEFA MORISHWALA    Mar-26         14        55368
                              VANDANA RAJPUT    Aug-25         22        55292
                         MOHEMADNAZIF SHAIKH    Jan-26         17        55254
                               SAJEED SAYYAD    Sep-25         14        54712
                               IRFAN HANSLOD    Jul-25         11        54653
                                INAYAT PATEL    Feb-26         16        54605
                         MOHEMADNAZIF SHAIKH    Jul-25         21        54503
                          NIMISHABAHEN PATEL    Aug-25         19        54488
                            JAGDISH AJMERIYA    Jun-26         14        54276
                                      VENU G    Jul-25         15        54246
                             JANAKBEN PARMAR    Aug-25         16        53634
                             RAMESH SANGEKAR    Jun-26         12        53368
                      MOHAMMEDHANEEF PATIDAR    May-26         12        53160
                   MOHAMMEDHUZEFA MORISHWALA    Aug-25         16        53094
                                 SURAJ KHODE    Feb-26         18        52575
                              SUSHANT REMAJE    Jun-26         18        52440
                        MOHAMMADSUFEL SHAIKH    Aug-25         22        52267
                               PRAVEEN SAROJ    Jan-26          4        52224
                   MOHAMMEDHUZEFA MORISHWALA    Jul-25         15        51860
                                Online Sales    Mar-26         16        51716
                          NIMISHABAHEN PATEL    Jul-25         12        51668
                           MOHAMMAD MOTIWALA    Mar-26         14        50872
                         MOHEMADNAZIF SHAIKH    Dec-25         15        50746
                         RAVINDERREDDY MUSKU    Oct-25         14        50578
                               WALK INN PUNE    Oct-25          9        50191
                                INAYAT PATEL    Mar-26         18        50069
                                  AMOL AARTE    Aug-25          9        48673
                                GANESH KANSE    May-26         19        48122
                                GANESH KANSE    Oct-25         13        48093
                              SUSHANT REMAJE    Oct-25          9        47928
                               SAJEED SAYYAD    Nov-25         13        47753
                           PRINCEKUMAR PATEL    Jul-25         16        47661
                             RAMESH SANGEKAR    Mar-26         13        47640
                               SAJEED SAYYAD    Mar-26         18        47502
                                INAYAT PATEL    Oct-25         15        47177
                             JANAKBEN PARMAR    Apr-26         14        47080
                         NASEEM AHMED SHAIKH    Jan-26          6        47048
                               IRFAN HANSLOD    May-26         12        46897
                            JAGDISH AJMERIYA    Apr-26         15        46764
                              SUSHANT REMAJE    Nov-25         11        46726
                             MD ZAFAR EQUBAL    Jul-25          8        46314
                             JANAKBEN PARMAR    Jun-26         14        46214
                           MOHAMMAD MOTIWALA    Jul-25         16        46171
                                ROHIT SHETTY    Nov-25         14        46049
                         MOHEMADNAZIF SHAIKH    Mar-26         15        46016
                                FARIZ LALANI    Sep-25         17        46013
                                ROHIT SHETTY    Oct-25         13        45938
                                GANESH KANSE    Feb-26         13        45471
                                ALMAS SHAIKH    Jul-25         13        45434
                                    VIKRAM R    Jul-25         16        45433
                                 AMOL JADHAV    Aug-25         10        45299
                             JANAKBEN PARMAR    Jan-26          9        45262
                             RAMESH SANGEKAR    Jul-25         15        44799
                              BHUMIKA PARMAR    Oct-25          9        44737
                              KISHAN SOLANKI    Nov-25         13        44686
                 KOLLI VENKATA NAGESWARA RAO    Apr-26         17        44602
                          SALAPU HARIKRISHNA    Jul-25         18        44525
                             RAMESH SANGEKAR    Apr-26         17        44390
                             RAMESH SANGEKAR    Sep-25         13        44010
                               IRFAN HANSLOD    Feb-26         11        43801
                            JAGDISH AJMERIYA    Sep-25         15        43796
                         MOHEMADNAZIF SHAIKH    Oct-25         13        43475
                         ABHILASH GOLLAPALLI    Jul-25         16        43429
                                    VIKRAM R    Oct-25         12        43376
                                Online Sales    Feb-26         14        43017
                          NIMISHABAHEN PATEL    Feb-26         13        42700
                              AVINASH SHEGAR    Jul-25         12        42678
                              MOAKRAM SHAIKH    Nov-25         12        42616
                                 SURAJ KHODE    Dec-25         11        42588
                                PRATIK PATEL    Dec-25          9        42577
                                IMRAN SHAIKH    Aug-25         15        42534
                              ANIL GANGARKAR    Nov-25         10        42486
                                    VIKRAM R    Aug-25         14        42376
                              VANDANA RAJPUT    Dec-25         14        42369
                               SAJEED SAYYAD    Jan-26         16        42173
                             MOHASHIN SHAIKH    Mar-26         12        42153
                              AMOL NAIKNAWRE    Oct-25         13        42139
                 KOLLI VENKATA NAGESWARA RAO    Jun-26         17        42102
                              SUSHANT REMAJE    Feb-26         12        41995
                               MUKESH NAGARE    Nov-25         11        41952
                             RAMESH SANGEKAR    May-26         15        41832
                      MOHAMMEDHANEEF PATIDAR    Feb-26         14        41768
                                 AMAR JACHAK    Jul-25         15        41506
                              ANIL GANGARKAR    Jan-26         10        41504
                           NILESH KHANDAGALE    Jul-25         10        41464
                           MOHAMMAD MOTIWALA    Aug-25         14        41380
                                INAYAT PATEL    May-26         11        41177
                               SAMEER HAFEJI    Mar-26         11        41177
                               BIDHAN MANDAL    Jul-25         13        41159
                              AVINASH SHEGAR    Aug-25         11        41075
                               SAJEED SAYYAD    May-26         14        41016
                    SATEESHREDDY JAGANNADHAM    Aug-25         19        40835
                         JAYLESHKUMAR PARMAR    Jul-25         12        40706
                              BHUMIKA PARMAR    Nov-25          8        40694
                         JAYLESHKUMAR PARMAR    Nov-25         11        40670
                               SAMEER HAFEJI    Nov-25         11        40583
                                JIMIT MACHHI    Mar-26         14        40467
                         NASEEM AHMED SHAIKH    Oct-25          5        40259
                               IRFAN HANSLOD    Jun-26         11        40245
                           MOHAMMAD MOTIWALA    Apr-26         14        40236
                               DINESH SHINDE    Oct-25          9        39943
                               SAMEER HAFEJI    Jun-26         10        39780
                        MOHAMMADSUFEL SHAIKH    Apr-26         10        39563
                                ROHIT SHETTY    Aug-25         12        39487
                             RAMNARESH YADAV    Aug-25         14        39478
                                  VICKY SHAH    Dec-25          9        39475
                               IRFAN HANSLOD    Jan-26         11        39354
                               SAJEED SAYYAD    Dec-25          9        39324
                                 AMAR JACHAK    Jan-26          9        39254
                             RAMNARESH YADAV    Nov-25         13        39057
                      KARAN UMESHSINGHRAJPUT    Sep-25         10        38900
                               SAJEED SAYYAD    Apr-26         14        38801
                             KEYUR GHADIYALI    Jan-26         12        38719
                              VANDANA RAJPUT    Mar-26         13        38687
                   MOHAMMEDHUZEFA MORISHWALA    Feb-26         14        38674
                              SUSHANT REMAJE    Aug-25         17        38646
                               IRFAN HANSLOD    Dec-25         12        38632
                              ANIL GANGARKAR    Jul-25         18        38574
                              ANIL GANGARKAR    May-26          9        38515
                            JAYDEEP KATUDIYA    Jul-25         17        38412
                 KOLLI VENKATA NAGESWARA RAO    Nov-25         13        38367
                                MAHESH PATEL    Nov-25         13        38329
                        MOHAMMADSUFEL SHAIKH    Nov-25         12        38210
                            JAGDISH AJMERIYA    Aug-25         11        37986
                                 SURAJ KHODE    Jan-26         12        37982
                            JAYDEEP KATUDIYA    Mar-26         14        37866
                              MOAKRAM SHAIKH    Feb-26         10        37787
                           RUPESH CHAURASIYA    Oct-25         10        37781
                                  VICKY SHAH    Jan-26         10        37703
                               RAVI VADOLIYA    Jul-25         11        37656
                              SUSHANT REMAJE    Jan-26         13        37647
                      MOHAMMEDHANEEF PATIDAR    Dec-25         10        37618
                               IRFAN HANSLOD    Aug-25         11        37534
                                  VICKY SHAH    Feb-26          8        37442
                              VANDANA RAJPUT    Jun-26         10        37303
                                   RAJ GUPTA    Jun-26          8        37103
                             JANAKBEN PARMAR    Dec-25         11        37024
                             JANAKBEN PARMAR    Oct-25          9        36983
                                      VENU G    Oct-25         10        36975
                         NASEEM AHMED SHAIKH    Jun-26          8        36943
                             RUCHITA KANSARA    Aug-25         10        36936
                              VANDANA RAJPUT    Jan-26         12        36767
                            JAYDEEP KATUDIYA    Jun-26          8        36724
                                JIMIT MACHHI    Apr-26         10        36715
                         MOHEMADNAZIF SHAIKH    May-26         15        36670
                           LAKSHMANARAO AVVA    Dec-25         14        36614
                             RAMNARESH YADAV    Oct-25         10        36611
                      MOHAMMEDHANEEF PATIDAR    Nov-25         11        36539
                              KAUSHIK VANKAR    Apr-26         12        36530
                              ANIL GANGARKAR    Dec-25         11        36522
                               YOGESH THAKUR    Oct-25          9        36417
                           SRINIVASRAO KOLLI    Jul-25         14        36387
                              BHUMIKA PARMAR    Apr-26         11        36232
                          NIMISHABAHEN PATEL    Nov-25          9        36202
                              AVINASH SHEGAR    Jun-26         12        36157
                            AFZALKHAN PATHAN    May-26         12        36134
                              BHUMIKA PARMAR    Dec-25          8        36134
                             SALMAN SABUVALA    Nov-25         10        36092
                             RAMNARESH YADAV    Dec-25         13        36043
                   MOHAMMEDHUZEFA MORISHWALA    Jan-26         11        36006
                               WALK INN PUNE    Sep-25          5        35952
                                  FARUQ SONI    Jun-26         11        35876
                               TAIYAB SHAIKH    Jul-25         11        35712
                           VIKASKUMAR SHARMA    Nov-25         10        35710
                              VANDANA RAJPUT    Oct-25          9        35669
                             GANTYADA NANAJI    Jun-26         10        35580
                               TAIYAB SHAIKH    May-26         11        35457
                              SUSHANT REMAJE    Dec-25         11        35394
                            AZAZAHMED NAGORI    May-26         12        35305
                                KALPESH MALI    Oct-25          8        35205
                               RAVI VADOLIYA    Sep-25          9        35076
                                KALPESH MALI    May-26          8        34926
                             MOHASHIN SHAIKH    Apr-26         11        34788
                              SUSHANT REMAJE    Sep-25         15        34706
                        ABDULFAIZAL RAJBHARA    Jan-26         11        34675
                              AVINASH SHEGAR    Apr-26         11        34655
                                INAYAT PATEL    Nov-25          8        34569
                               TAIYAB SHAIKH    Aug-25         10        34552
                          SALAPU HARIKRISHNA    Jun-26         10        34551
                             SALMAN SABUVALA    Apr-26         10        34338
                      MOHAMMEDHANEEF PATIDAR    Jan-26         11        34310

In [24]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# --- SLA ageing ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- Executive monthly totals ---
exec_monthly = df.groupby(["SALES EXEC NAME", "MonthYear"]).agg(
    Customers=("ACCOUNT NO", "count"),
    Total_Value=("Plan Value", "sum")
).reset_index()

# --- Pivot: months as columns ---
pivot_customers = exec_monthly.pivot(index="SALES EXEC NAME", columns="MonthYear", values="Customers").fillna(0)
pivot_value = exec_monthly.pivot(index="SALES EXEC NAME", columns="MonthYear", values="Total_Value").fillna(0)

# --- Combine Customers + Value side-by-side ---
combined = pd.DataFrame(index=pivot_customers.index)

for month in pivot_customers.columns:
    combined[f"{month}_Cust"] = pivot_customers[month].round(0)
    combined[f"{month}_Value"] = pivot_value[month].round(0)

# --- Yearly totals and averages ---
combined["Yearly_Customers"] = combined.filter(like="_Cust").sum(axis=1).round(0)
combined["Yearly_Value"] = combined.filter(like="_Value").sum(axis=1).round(0)
combined["Avg_Customers_per_Month"] = (combined["Yearly_Customers"] / 12).round(0)
combined["Avg_Value_per_Month"] = (combined["Yearly_Value"] / 12).round(0)

# --- Sort high → low by yearly value and customers ---
combined = combined.sort_values(by=["Yearly_Value","Yearly_Customers"], ascending=False).reset_index()

# --- Print clean table ---
print(combined.to_string(index=False))

                             SALES EXEC NAME  Apr-25_Cust  Apr-25_Value  Apr-26_Cust  Apr-26_Value  Aug-25_Cust  Aug-25_Value  Dec-25_Cust  Dec-25_Value  Feb-26_Cust  Feb-26_Value  Jan-26_Cust  Jan-26_Value  Jul-25_Cust  Jul-25_Value  Jun-25_Cust  Jun-25_Value  Jun-26_Cust  Jun-26_Value  Mar-25_Cust  Mar-25_Value  Mar-26_Cust  Mar-26_Value  May-25_Cust  May-25_Value  May-26_Cust  May-26_Value  Nov-25_Cust  Nov-25_Value  Oct-25_Cust  Oct-25_Value  Sep-25_Cust  Sep-25_Value  Yearly_Customers  Yearly_Value  Avg_Customers_per_Month  Avg_Value_per_Month
                                Online Sales          0.0           0.0         23.0       66792.0         40.0      108109.0         25.0       86001.0         14.0       43017.0         19.0       58277.0         50.0      134954.0          4.0        7659.0         31.0       87820.0          0.0           0.0         16.0       51716.0          1.0        3215.0         21.0       81359.0         30.0       92052.0          8.0       27385.0         30.0       94336.0             312.0      942692.0                     26.0              78558.0
                                GANESH KANSE          0.0           0.0         23.0       90735.0         25.0       79628.0         21.0       70033.0         13.0       45471.0         16.0       62528.0         22.0       60152.0          2.0        3786.0         21.0       82712.0          0.0           0.0         18.0       93285.0          0.0           0.0         19.0       48122.0         22.0       74267.0         13.0       48093.0         22.0       78728.0             237.0      837540.0                     20.0              69795.0
                         MOHEMADNAZIF SHAIKH          0.0           0.0         21.0       62732.0         30.0       94523.0         15.0       50746.0         20.0       63661.0         17.0       55254.0         21.0       54503.0          4.0        8896.0         21.0       67190.0          0.0           0.0         15.0       46016.0          0.0           0.0         15.0       36670.0         16.0       57101.0         13.0       43475.0         10.0       34061.0             218.0      674828.0                     18.0              56236.0
                               SAJEED SAYYAD          0.0           0.0         14.0       38801.0         19.0       61762.0          9.0       39324.0         14.0       33523.0         16.0       42173.0         20.0       59757.0          0.0           0.0          8.0       26736.0          0.0           0.0         18.0       47502.0          0.0           0.0         14.0       41016.0         13.0       47753.0         15.0       60918.0         14.0       54712.0             174.0      553977.0                     14.0              46165.0
                              VANDANA RAJPUT          0.0           0.0         15.0       60621.0         22.0       55292.0         14.0       42369.0          6.0       22759.0         12.0       36767.0         23.0       78050.0          4.0       16467.0         10.0       37303.0          1.0        9600.0         13.0       38687.0          0.0           0.0          8.0       28628.0         10.0       28744.0          9.0       35669.0         11.0       32787.0             158.0      523743.0                     13.0              43645.0
                              SUSHANT REMAJE          0.0           0.0         15.0       56917.0         17.0       38646.0         11.0       35394.0         12.0       41995.0         13.0       37647.0         18.0       63780.0          0.0           0.0         18.0       52440.0          0.0           0.0         11.0       32594.0          0.0           0.0         12.0       32125.0         11.0       46726.0          9.0       47928.0         15.0       34706.0             162.0      520898.0                     14.0              43408.0
                             JANAKBEN PARMAR          0.0           0.0         14.0       47080.0         16.0       53634.0         11.0       37024.0          6.0       17832.0          9.0       45262.0         22.0       69986.0          0.0           0.0         14.0       46214.0          0.0           0.0         11.0       26519.0          0.0           0.0         16.0       57432.0         15.0       63819.0          9.0       36983.0          5.0       17624.0             148.0      519409.0                     12.0              43284.0
                            JAGDISH AJMERIYA          0.0           0.0         15.0       46764.0         11.0       37986.0          6.0       30758.0          2.0        5591.0          5.0       13003.0         21.0       82131.0          0.0           0.0         14.0       54276.0          0.0           0.0          8.0       32077.0          0.0           0.0          8.0       31094.0         13.0       59480.0         15.0       65156.0         15.0       43796.0             133.0      502112.0                     11.0              41843.0
                                INAYAT PATEL          0.0           0.0          9.0       23636.0         22.0       70462.0         10.0       30415.0         16.0       54605.0          8.0       24060.0         16.0       58352.0          3.0        8811.0          9.0       29102.0          0.0           0.0         18.0       50069.0          0.0           0.0         11.0       41177.0          8.0       34569.0         15.0       47177.0          8.0       26326.0             153.0      498761.0                     13.0              41563.0
                      MOHAMMEDHANEEF PATIDAR          0.0           0.0          9.0       27195.0         18.0       61942.0         10.0       37618.0         14.0       41768.0         11.0       34310.0         20.0       59138.0          2.0        4660.0          8.0       21605.0          0.0           0.0         10.0       26220.0          0.0           0.0         12.0       53160.0         11.0       36539.0         12.0       28967.0         10.0       30246.0             147.0      463368.0                     12.0              38614.0
                               SAMEER HAFEJI          0.0           0.0          8.0       24951.0         16.0       59042.0          8.0       29908.0          9.0       28000.0         10.0       28321.0         23.0       73478.0          0.0           0.0         10.0       39780.0          0.0           0.0         11.0       41177.0          0.0           0.0          9.0       26687.0         11.0       40583.0          8.0       21082.0          7.0       21571.0             130.0      434580.0                     11.0              36215.0
                               IRFAN HANSLOD          0.0           0.0         11.0       31639.0         11.0       37534.0         12.0       38632.0         11.0       43801.0         11.0       39354.0         11.0       54653.0          0.0           0.0         11.0       40245.0          0.0           0.0          6.0       15333.0          0.0           0.0         12.0       46897.0         10.0       33127.0          8.0       27366.0          8.0       22028.0             122.0      430609.0                     10.0              35884.0
                             RAMESH SANGEKAR          0.0           0.0         17.0       44390.0          8.0       16898.0         12.0       33986.0          9.0       26982.0          7.0       14865.0         15.0       44799.0          0.0           0.0         12.0       53368.0          0.0           0.0         13.0       47640.0          0.0           0.0         15.0       41832.0          8.0       25425.0          6.0       26008.0         13.0       44010.0             135.0      420203.0                     11.0              35017.0
                   MOHAMMEDHUZEFA MORISHWALA          0.0           0.0          9.0       15374.0         16.0       53094.0          8.0       28044.0         14.0       38674.0         11.0       36006.0         15.0       51860.0          1.0        4914.0          0.0           0.0          0.0           0.0         14.0       55368.0          0.0           0.0         11.0       30329.0          9.0       33721.0          8.0       30088.0         10.0       29591.0             126.0      407063.0                     10.0              33922.0
                              BHUMIKA PARMAR          0.0           0.0         11.0       36232.0         11.0       32174.0          8.0       36134.0          8.0       22644.0          9.0       30447.0         11.0       34066.0          0.0           0.0          6.0       23575.0          0.0           0.0         10.0       29401.0          0.0           0.0          7.0       19315.0          8.0       40694.0          9.0       44737.0          9.0       32671.0             107.0      382090.0                      9.0              31841.0
                           MOHAMMAD MOTIWALA          0.0           0.0         14.0       40236.0         14.0       41380.0          9.0       23128.0         10.0       28128.0          9.0       27366.0         16.0       46171.0          0.0           0.0          9.0       24398.0          0.0           0.0         14.0       50872.0          0.0           0.0         11.0       26389.0          9.0       33212.0          8.0       20911.0          8.0       18132.0             131.0      380323.0                     11.0              31694.0
                        MOHAMMADSUFEL SHAIKH          0.0           0.0         10.0       39563.0         22.0       52267.0          9.0       30584.0          8.0       28533.0          2.0        9490.0         11.0       33043.0          1.0        3728.0          7.0       23764.0          0.0           0.0          9.0       30711.0          0.0           0.0          9.0       28795.0         12.0       38210.0          9.0       22953.0          8.0       21136.0             117.0      362777.0                     10.0              30231.0
                               TAIYAB SHAIKH          0.0           0.0         11.0       29821.0         10.0       34552.0          8.0       22154.0         11.0       29166.0         10.0       32534.0         11.0       35712.0          0.0           0.0          9.0       31009.0          0.0           0.0         10.0       28635.0          0.0           0.0         11.0       35457.0         11.0       32871.0          8.0       24146.0          8.0       23976.0             118.0      360033.0                     10.0              30003.0
                              MOAKRAM SHAIKH          0.0           0.0          8.0       17577.0         10.0       34240.0          8.0       23298.0         10.0       37787.0          9.0       31937.0         11.0       33028.0          1.0        3343.0          7.0       27367.0          0.0           0.0          9.0       26178.0          0.0           0.0         11.0       30160.0         12.0       42616.0          9.0       23880.0          9.0       23894.0             114.0      355305.0                     10.0              29609.0
                              ANIL GANGARKAR          0.0           0.0          3.0       13203.0          8.0       13848.0         11.0       36522.0          5.0       12422.0         10.0       41504.0         18.0       38574.0          1.0        2031.0         12.0       30367.0          0.0           0.0         11.0       25603.0          0.0           0.0          9.0       38515.0         10.0       42486.0          8.0       30475.0         10.0       28334.0             116.0      353884.0                     10.0              29490.0
                                 SURAJ KHODE          0.0           0.0          8.0       19966.0         11.0       21461.0         11.0       42588.0         18.0       52575.0         12.0       37982.0         11.0       33198.0          0.0           0.0         12.0       33785.0          0.0           0.0          8.0       25106.0          0.0           0.0          8.0       17690.0          2.0        5308.0          8.0       23450.0         11.0       33789.0             120.0      346898.0                     10.0              28908.0
                 KOLLI VENKATA NAGESWARA RAO          0.0           0.0         17.0       44602.0         12.0       28438.0          9.0       28451.0         10.0       18381.0         13.0       28432.0         10.0       19719.0          0.0           0.0         17.0       42102.0          0.0           0.0         12.0       26615.0          0.0           0.0         13.0       24358.0         13.0       38367.0          6.0       18297.0         10.0       28802.0             142.0      346564.0                     12.0              28880.0
                            JAYDEEP KATUDIYA          0.0           0.0         12.0       30490.0         14.0       27135.0         12.0       25597.0         10.0       22611.0         10.0       27091.0         17.0       38412.0          1.0        2542.0          8.0       36724.0          0.0           0.0         14.0       37866.0          0.0           0.0          7.0       31512.0          5.0       13735.0          8.0       26173.0          6.0       20179.0             124.0      340067.0                     10.0              28339.0
                                  VICKY SHAH          0.0           0.0          7.0       29485.0          8.0       23992.0          9.0       39475.0          8.0       37442.0         10.0       37703.0          9.0       23886.0          0.0           0.0          5.0       16012.0          0.0           0.0          9.0       30414.0          0.0           0.0          9.0       31088.0         10.0       31770.0          7.0       16448.0          9.0       21553.0             100.0      339268.0                      8.0              28272.0
                         NASEEM AHMED SHAIKH          0.0           0.0          8.0       32956.0          9.0       25817.0          4.0       16719.0          7.0       19779.0          6.0       47048.0          7.0       18647.0          0.0           0.0          8.0       36943.0          0.0           0.0          8.0       31948.0          0.0           0.0          9.0       31062.0          3.0       10210.0          5.0       40259.0          8.0       26163.0              82.0      337551.0                      7.0              28129.0
                              AVINASH SHEGAR          0.0           0.0         11.0       34655.0         11.0       41075.0          8.0       23075.0          7.0       24146.0          8.0       21598.0         12.0       42678.0          0.0           0.0         12.0       36157.0          0.0           0.0         11.0       26838.0          0.0           0.0          9.0       19865.0          5.0       15352.0          8.0       26390.0          8.0       23607.0             110.0      335436.0                      9.0              27953.0
                        ABDULFAIZAL RAJBHARA          0.0           0.0          9.0       20034.0         11.0       29254.0         12.0       29141.0         11.0       33041.0         11.0       34675.0         12.0       29188.0          0.0           0.0          8.0       15375.0          0.0           0.0          9.0       31602.0          0.0           0.0         12.0       31219.0          9.0       24060.0          9.0       24229.0          9.0       28890.0             122.0      330708.0                     10.0              27559.0
                               DINESH SHINDE          0.0           0.0          7.0       22740.0          8.0       22608.0          8.0       31303.0          4.0       14463.0          8.0       33215.0         11.0       27863.0          2.0        4465.0          7.0       28851.0          0.0           0.0          6.0       20425.0          0.0           0.0          8.0       27831.0          7.0       27364.0          9.0       39943.0          8.0       22674.0              93.0      323745.0                      8.0              26979.0
                          SALAPU HARIKRISHNA          0.0           0.0          9.0       23523.0          8.0       20021.0          9.0       27338.0          9.0       30906.0          7.0       19666.0         18.0       44525.0          0.0           0.0         10.0       34551.0          0.0           0.0         10.0       22843.0          0.0           0.0         10.0       25634.0          9.0       26741.0          6.0       19434.0          8.0       23353.0             113.0      318535.0                      9.0              26545.0
                                IMRAN SHAIKH          0.0           0.0          9.0       24137.0         15.0       42534.0          8.0       24823.0          7.0       19731.0          8.0       29139.0         11.0       27394.0          1.0        1200.0          8.0       22069.0          0.0           0.0          6.0       22113.0          0.0           0.0          8.0       24823.0          7.0       19486.0         11.0       33321.0          8.0       27191.0             107.0      317961.0                      9.0              26497.0
                                JIMIT MACHHI          0.0           0.0         10.0       36715.0         12.0       24861.0          9.0       24678.0          9.0       24530.0          5.0       14756.0         26.0       56051.0          1.0        1500.0         10.0       25116.0          0.0           0.0         14.0       40467.0          0.0           0.0          6.0       14109.0          6.0       17028.0          5.0       15711.0          8.0       20106.0             121.0      315628.0                     10.0              26302.0
                             SALMAN SABUVALA          0.0           0.0         10.0       34338.0         11.0       26200.0          9.0       25754.0          8.0       22874.0          8.0       17621.0          8.0       22579.0          0.0           0.0          7.0       23808.0          0.0           0.0         12.0       25964.0          0.0           0.0         11.0       29693.0         10.0       36092.0         10.0       26866.0          9.0       22454.0             113.0      314243.0                      9.0              26187.0
                          NIMISHABAHEN PATEL          0.0           0.0          9.0       18001.0         19.0       54488.0          1.0        2227.0         13.0       42700.0          8.0       29055.0         12.0       51668.0          2.0        5846.0          0.0           0.0          0.0           0.0          8.0       16688.0          0.0           0.0          2.0        8219.0          9.0       36202.0          9.0       30148.0          5.0       13793.0              97.0      309035.0                      8.0              25753.0
                                 AMAR JACHAK          0.0           0.0         10.0       21408.0         12.0       30643.0          8.0       26020.0         10.0       25382.0          9.0       39254.0         15.0       41506.0          0.0           0.0          6.0       19801.0          0.0           0.0          8.0       23243.0          0.0           0.0         11.0       29474.0          6.0       17160.0          1.0        4504.0         10.0       29728.0             106.0      308123.0                      9.0              25677.0
                         JAYLESHKUMAR PARMAR          0.0           0.0          9.0       19283.0          9.0       27504.0          8.0       22278.0          8.0       19965.0          8.0       22025.0         12.0       40706.0          0.0           0.0          6.0       17782.0          0.0           0.0          8.0       23891.0          0.0           0.0         10.0       28454.0         11.0       40670.0          7.0       26087.0          6.0       16605.0             102.0      305250.0                      8.0              25438.0

In [25]:
import pandas as pd

# Assume df is cleaned with MonthYear, SLA, etc.

# Pivot for executive summary
pivot = df.pivot_table(
    index="SALES EXEC NAME",
    columns="MonthYear",
    values=["ACCOUNT NO","Plan Value"],
    aggfunc={"ACCOUNT NO":"count","Plan Value":"sum"},
    fill_value=0
)

# Flatten columns
pivot.columns = [f"{month}_{metric}" for metric, month in pivot.columns]

# Add totals and averages
pivot["Yearly_Customers"] = pivot.filter(like="_ACCOUNT NO").sum(axis=1).round(0)
pivot["Yearly_Value"] = pivot.filter(like="_Plan Value").sum(axis=1).round(0)
pivot["Avg_Customers_per_Month"] = (pivot["Yearly_Customers"]/12).round(0)
pivot["Avg_Value_per_Month"] = (pivot["Yearly_Value"]/12).round(0)

# Sort
pivot = pivot.sort_values(by=["Yearly_Value","Yearly_Customers"], ascending=False).reset_index()

In [26]:
import pandas as pd
import streamlit as st

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- SLA ageing ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

# --- Filters ---
manager = st.selectbox("Select Manager", ["All"] + sorted(df["SALES MANGER NAME"].dropna().unique()))
city = st.selectbox("Select City", ["All"] + sorted(df["City"].dropna().unique()))
execu = st.selectbox("Select Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))
speed = st.selectbox("Select Speed", ["All"] + sorted(df["SPEED (Mbps)"].dropna().unique()))
validity = st.selectbox("Select Validity", ["All"] + sorted(df["VALIDITY In Months"].dropna().unique()))
plan = st.selectbox("Select Plan", ["All"] + sorted(df["REGISTRATION PLAN"].dropna().unique()))

# --- Apply filters ---
filtered = df.copy()
if manager != "All": filtered = filtered[filtered["SALES MANGER NAME"] == manager]
if city != "All": filtered = filtered[filtered["City"] == city]
if execu != "All": filtered = filtered[filtered["SALES EXEC NAME"] == execu]
if speed != "All": filtered = filtered[filtered["SPEED (Mbps)"] == speed]
if validity != "All": filtered = filtered[filtered["VALIDITY In Months"] == validity]
if plan != "All": filtered = filtered[filtered["REGISTRATION PLAN"] == plan]

# --- Pivot executive summary ---
pivot = filtered.pivot_table(
    index="SALES EXEC NAME",
    columns="MonthYear",
    values=["ACCOUNT NO","Plan Value"],
    aggfunc={"ACCOUNT NO":"count","Plan Value":"sum"},
    fill_value=0
)

pivot.columns = [f"{month}_{metric}" for metric, month in pivot.columns]

pivot["Yearly_Customers"] = pivot.filter(like="_ACCOUNT NO").sum(axis=1).round(0)
pivot["Yearly_Value"] = pivot.filter(like="_Plan Value").sum(axis=1).round(0)
pivot["Avg_Customers_per_Month"] = (pivot["Yearly_Customers"]/12).round(0)
pivot["Avg_Value_per_Month"] = (pivot["Yearly_Value"]/12).round(0)

pivot = pivot.sort_values(by=["Yearly_Value","Yearly_Customers"], ascending=False).reset_index()

# --- Show table ---
st.dataframe(pivot)

ModuleNotFoundError: No module named 'streamlit'

In [27]:
streamlit run dashboard.py

SyntaxError: invalid syntax (512221001.py, line 1)

In [28]:
C:\Users\Harshal Thakkar\dashboard.py

SyntaxError: unexpected character after line continuation character (2238804404.py, line 1)

In [29]:
streamlit run dashboard.py

SyntaxError: invalid syntax (512221001.py, line 1)

In [30]:
# --- SLA ageing ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [31]:
if "SLA_Category" in filtered.columns and not filtered.empty:
    sla_chart = filtered.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
    fig_sla = px.bar(sla_chart, x="SLA_Category", y="ACCOUNT NO", title="SLA Distribution")
    st.plotly_chart(fig_sla)
else:
    st.warning("No SLA data available for the current filter selection.")

NameError: name 'filtered' is not defined

In [32]:
# --- Apply filters ---
filtered = df.copy()
if manager != "All": filtered = filtered[filtered["SALES MANGER NAME"] == manager]
if city != "All": filtered = filtered[filtered["City"] == city]
if execu != "All": filtered = filtered[filtered["SALES EXEC NAME"] == execu]
if speed != "All": filtered = filtered[filtered["SPEED (Mbps)"] == speed]
if validity != "All": filtered = filtered[filtered["VALIDITY In Months"] == validity]
if plan != "All": filtered = filtered[filtered["REGISTRATION PLAN"] == plan]

# --- SLA Distribution Chart ---
if "SLA_Category" in filtered.columns and not filtered.empty:
    sla_chart = filtered.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
    fig_sla = px.bar(sla_chart, x="SLA_Category", y="ACCOUNT NO", title="SLA Distribution")
    st.plotly_chart(fig_sla)
else:
    st.warning("No SLA data available for the current filter selection.")

NameError: name 'manager' is not defined

In [33]:
manager = st.sidebar.selectbox("Manager", ["All"] + sorted(df["SALES MANGER NAME"].dropna().unique()))
city = st.sidebar.selectbox("City", ["All"] + sorted(df["City"].dropna().unique()))
execu = st.sidebar.selectbox("Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))
speed = st.sidebar.selectbox("Speed (Mbps)", ["All"] + sorted(df["SPEED (Mbps)"].dropna().unique()))
validity = st.sidebar.selectbox("Validity (Months)", ["All"] + sorted(df["VALIDITY In Months"].dropna().unique()))
plan = st.sidebar.selectbox("Plan", ["All"] + sorted(df["REGISTRATION PLAN"].dropna().unique()))

NameError: name 'st' is not defined

In [34]:
if not filtered.empty:
    if "SLA_Category" in filtered.columns:
        sla_chart = filtered.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
        fig_sla = px.bar(sla_chart, x="SLA_Category", y="ACCOUNT NO", title="SLA Distribution")
        st.plotly_chart(fig_sla)
    else:
        st.warning("SLA_Category column not found in filtered data.")
else:
    st.warning("No data available for the current filter selection.")

NameError: name 'px' is not defined

In [36]:
# --- SLA ageing ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [37]:
# --- Filters ---
st.sidebar.header("Filters")
manager = st.sidebar.selectbox("Manager", ["All"] + sorted(df["SALES MANGER NAME"].dropna().unique()))
city = st.sidebar.selectbox("City", ["All"] + sorted(df["City"].dropna().unique()))
execu = st.sidebar.selectbox("Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))

# Convert numeric filters to strings for readability
speed_options = ["All"] + [str(int(s)) for s in sorted(df["SPEED (Mbps)"].dropna().unique())]
speed = st.sidebar.selectbox("Speed (Mbps)", speed_options)

validity_options = ["All"] + [str(int(v)) for v in sorted(df["VALIDITY In Months"].dropna().unique())]
validity = st.sidebar.selectbox("Validity (Months)", validity_options)

plan = st.sidebar.selectbox("Plan", ["All"] + sorted(df["REGISTRATION PLAN"].dropna().unique()))

NameError: name 'st' is not defined

In [38]:
import pandas as pd
import streamlit as st
import plotly.express as px

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")
df["MonthYear"] = df["CREATION DATE"].dt.strftime("%b-%y")

# --- SLA ageing + SLA_Category ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Sidebar Filters ---
st.sidebar.header("Filters")
manager = st.sidebar.selectbox("Manager", ["All"] + sorted(df["SALES MANGER NAME"].dropna().unique()))
city = st.sidebar.selectbox("City", ["All"] + sorted(df["City"].dropna().unique()))
execu = st.sidebar.selectbox("Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))

# Convert numeric filters to strings for readability
speed_options = ["All"] + [str(int(s)) for s in sorted(df["SPEED (Mbps)"].dropna().unique())]
speed = st.sidebar.selectbox("Speed (Mbps)", speed_options)

validity_options = ["All"] + [str(int(v)) for v in sorted(df["VALIDITY In Months"].dropna().unique())]
validity = st.sidebar.selectbox("Validity (Months)", validity_options)

plan = st.sidebar.selectbox("Plan", ["All"] + sorted(df["REGISTRATION PLAN"].dropna().unique()))

# --- Apply filters ---
filtered = df.copy()
if manager != "All": filtered = filtered[filtered["SALES MANGER NAME"] == manager]
if city != "All": filtered = filtered[filtered["City"] == city]
if execu != "All": filtered = filtered[filtered["SALES EXEC NAME"] == execu]
if speed != "All": filtered = filtered[filtered["SPEED (Mbps)"] == int(speed)]
if validity != "All": filtered = filtered[filtered["VALIDITY In Months"] == int(validity)]
if plan != "All": filtered = filtered[filtered["REGISTRATION PLAN"] == plan]

# --- Executive Summary Table ---
pivot = filtered.pivot_table(
    index="SALES EXEC NAME",
    columns="MonthYear",
    values=["ACCOUNT NO","Plan Value"],
    aggfunc={"ACCOUNT NO":"count","Plan Value":"sum"},
    fill_value=0
)

pivot.columns = [f"{month}_{metric}" for metric, month in pivot.columns]
pivot["Yearly_Customers"] = pivot.filter(like="_ACCOUNT NO").sum(axis=1).round(0)
pivot["Yearly_Value"] = pivot.filter(like="_Plan Value").sum(axis=1).round(0)
pivot["Avg_Customers_per_Month"] = (pivot["Yearly_Customers"]/12).round(0)
pivot["Avg_Value_per_Month"] = (pivot["Yearly_Value"]/12).round(0)
pivot = pivot.sort_values(by=["Yearly_Value","Yearly_Customers"], ascending=False).reset_index()

st.title("Executive Summary Dashboard")
st.dataframe(pivot)

# --- SLA Distribution Chart ---
if not filtered.empty and "SLA_Category" in filtered.columns:
    sla_chart = filtered.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
    fig_sla = px.bar(sla_chart, x="SLA_Category", y="ACCOUNT NO", title="SLA Distribution")
    st.plotly_chart(fig_sla)
else:
    st.warning("No SLA data available for the current filter selection.")

2026-07-28 17:04:51.609 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.958
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Harshal Thakkar\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Session state does not function when running a script without `streamlit run`
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.974 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.976 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.977 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.980 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.994 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:51.998 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.019 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 17:04:52.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [39]:
import pandas as pd

# Reload the corrected dataset
df = pd.read_csv("Registration Report.csv")

# Quick check
print(df.shape)
print(df.columns)
df.head()

(14033, 14)
Index(['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO',
       'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT',
       'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value',
       'SPEED (Mbps)', 'VALIDITY In Months'],
      dtype='str')

,City,CREATION DATE,INSTALLATION DATE,ACCOUNT NO,CURRENT STATUS,SALES EXEC NAME,SALES MANGER NAME,DEPARTMENT,INSTALLATION NODE,NETWORK TYPE,REGISTRATION PLAN,Plan Value,SPEED (Mbps),VALIDITY In Months
0,VADODARA,27-06-2025,01-07-2025,2286083,ACTIVE,BHAVITABEN THAKKAR,RAJIV BHATIYA,Sales Direct,G-KARMAJ-02-07C01VA14,GPON,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3
1,PUNE,28-06-2025,01-07-2025,2285899,SUSPEND,Online Sales,Manish Sarode,Online Sales,SW-EVES,MEN,13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...,1076,60,3
2,PUNE,28-06-2025,01-07-2025,2286084,SUSPEND,JAVED SHAIKH,Manish Sarode,TECH SUPPORT,SW-KMALHAR,MEN,12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...,4572,125,6
3,PUNE,28-06-2025,01-07-2025,2286085,SUSPEND,SUGRIV JOGDAND,Manish Sarode,TECH SUPPORT,G-LMD-02-02C01PE29,GPON,13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...,2913,200,3
4,VADODARA,28-06-2025,01-07-2025,2286092,SUSPEND,RAHILKHA SOLANKI,RAJIV BHATIYA,TECH SUPPORT,MAHEFUJ-VADCARD07,HFC,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3

In [40]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Month-Year based on Installation Date
df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

In [41]:
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [42]:
import plotly.express as px

exec_name = "GANESH KANSE"
exec_data = df[df["SALES EXEC NAME"] == exec_name]

speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"Installation count"}, inplace=True)

fig = px.pie(speed_dist, names="SPEED (Mbps)", values="Installation count",
             title=f"{exec_name} Speed Distribution")
fig.show()

In [43]:
exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)

In [44]:
fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                      text="Value", title=f"{exec_name} Month-wise Performance")
fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")

In [45]:
fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
fig_exec_speed.update_traces(textinfo="label+percent")

ValueError: Value of 'values' is not the name of a column in 'data_frame'. Expected one of ['SPEED (Mbps)', 'Installation count'] but received: No. of Installations

In [46]:
speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_exec_speed = px.pie(speed_dist,
                        names="SPEED (Mbps)",
                        values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
# Show speed labels + % contribution inside the pie
fig_exec_speed.update_traces(textinfo="label+percent")
st.plotly_chart(fig_exec_speed)

2026-07-28 18:42:24.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:42:24.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:42:24.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:42:24.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:42:24.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [47]:
speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_exec_speed = px.pie(speed_dist,
                        names="SPEED (Mbps)",
                        values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
# Show speed labels + % contribution inside the pie
fig_exec_speed.update_traces(textinfo="label+percent")
st.plotly_chart(fig_exec_speed)

2026-07-28 18:43:37.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:43:37.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:43:37.237 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:43:37.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 18:43:37.238 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [48]:
import pandas as pd
import plotly.express as px

# Load corrected dataset
df = pd.read_csv("Registration Report.csv")

# Quick check
print(df.shape)
print(df.columns)
df.head()

(14033, 14)
Index(['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO',
       'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT',
       'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value',
       'SPEED (Mbps)', 'VALIDITY In Months'],
      dtype='str')

,City,CREATION DATE,INSTALLATION DATE,ACCOUNT NO,CURRENT STATUS,SALES EXEC NAME,SALES MANGER NAME,DEPARTMENT,INSTALLATION NODE,NETWORK TYPE,REGISTRATION PLAN,Plan Value,SPEED (Mbps),VALIDITY In Months
0,VADODARA,27-06-2025,01-07-2025,2286083,ACTIVE,BHAVITABEN THAKKAR,RAJIV BHATIYA,Sales Direct,G-KARMAJ-02-07C01VA14,GPON,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3
1,PUNE,28-06-2025,01-07-2025,2285899,SUSPEND,Online Sales,Manish Sarode,Online Sales,SW-EVES,MEN,13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...,1076,60,3
2,PUNE,28-06-2025,01-07-2025,2286084,SUSPEND,JAVED SHAIKH,Manish Sarode,TECH SUPPORT,SW-KMALHAR,MEN,12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...,4572,125,6
3,PUNE,28-06-2025,01-07-2025,2286085,SUSPEND,SUGRIV JOGDAND,Manish Sarode,TECH SUPPORT,G-LMD-02-02C01PE29,GPON,13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...,2913,200,3
4,VADODARA,28-06-2025,01-07-2025,2286092,SUSPEND,RAHILKHA SOLANKI,RAJIV BHATIYA,TECH SUPPORT,MAHEFUJ-VADCARD07,HFC,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3

In [49]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Month-Year based on Installation Date
df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

In [50]:
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [51]:
sla_chart = df.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
sla_chart.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)
sla_chart["Percent"] = (sla_chart["No. of Installations"] /
                        sla_chart["No. of Installations"].sum() * 100).round(1)

fig_sla = px.bar(sla_chart, x="SLA_Category", y="No. of Installations",
                 text=sla_chart.apply(lambda row: f"{row['No. of Installations']} ({row['Percent']}%)", axis=1),
                 title="All India SLA Distribution")
fig_sla.update_traces(textposition="outside")
fig_sla.show()

In [52]:
month_trend = df.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
month_trend.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
month_trend = month_trend.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_month = px.bar(month_trend, x="MonthYear", y="No. of Installations", text="Value",
                   title="All India Month-wise Installations")
fig_month.update_traces(textposition="outside")
fig_month.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_month.show()

In [53]:
speed_pattern = df.groupby(["SPEED (Mbps)"])["ACCOUNT NO"].count().reset_index()
speed_pattern.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_speed = px.bar(speed_pattern, x="SPEED (Mbps)", y="No. of Installations",
                   title="All India Speed-wise Installation Count", text="No. of Installations")
fig_speed.update_traces(textposition="outside")
fig_speed.update_layout(bargap=0.2, height=600,
                        xaxis=dict(dtick=50, range=[0,500]))
fig_speed.show()

In [54]:
exec_name = "GANESH KANSE"
exec_data = df[df["SALES EXEC NAME"] == exec_name]

# Speed distribution pie chart
speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
fig_exec_speed.update_traces(textinfo="label+percent")
fig_exec_speed.show()

# Month-wise installations + value
exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
exec_month = exec_month.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                      text="Value", title=f"{exec_name} Month-wise Performance")
fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_exec_bar.update_traces(textposition="outside")
fig_exec_bar.show()

In [55]:
import pandas as pd
import plotly.express as px

# Load corrected dataset
df = pd.read_csv("Registration Report.csv")

print(df.shape)
print(df.columns)
df.head()

(14033, 14)
Index(['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO',
       'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT',
       'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value',
       'SPEED (Mbps)', 'VALIDITY In Months'],
      dtype='str')

,City,CREATION DATE,INSTALLATION DATE,ACCOUNT NO,CURRENT STATUS,SALES EXEC NAME,SALES MANGER NAME,DEPARTMENT,INSTALLATION NODE,NETWORK TYPE,REGISTRATION PLAN,Plan Value,SPEED (Mbps),VALIDITY In Months
0,VADODARA,27-06-2025,01-07-2025,2286083,ACTIVE,BHAVITABEN THAKKAR,RAJIV BHATIYA,Sales Direct,G-KARMAJ-02-07C01VA14,GPON,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3
1,PUNE,28-06-2025,01-07-2025,2285899,SUSPEND,Online Sales,Manish Sarode,Online Sales,SW-EVES,MEN,13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...,1076,60,3
2,PUNE,28-06-2025,01-07-2025,2286084,SUSPEND,JAVED SHAIKH,Manish Sarode,TECH SUPPORT,SW-KMALHAR,MEN,12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...,4572,125,6
3,PUNE,28-06-2025,01-07-2025,2286085,SUSPEND,SUGRIV JOGDAND,Manish Sarode,TECH SUPPORT,G-LMD-02-02C01PE29,GPON,13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...,2913,200,3
4,VADODARA,28-06-2025,01-07-2025,2286092,SUSPEND,RAHILKHA SOLANKI,RAJIV BHATIYA,TECH SUPPORT,MAHEFUJ-VADCARD07,HFC,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3

In [56]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

In [57]:
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [58]:
sla_chart = df.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
sla_chart.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)
sla_chart["Percent"] = (sla_chart["No. of Installations"] /
                        sla_chart["No. of Installations"].sum() * 100).round(1)

fig_sla = px.bar(sla_chart, x="SLA_Category", y="No. of Installations",
                 text=sla_chart.apply(lambda row: f"{row['No. of Installations']} ({row['Percent']}%)", axis=1),
                 title="All India SLA Distribution")
fig_sla.update_traces(textposition="outside")
fig_sla.show()

In [59]:
month_trend = df.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
month_trend.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
month_trend = month_trend.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_month = px.bar(month_trend, x="MonthYear", y="No. of Installations", text="Value",
                   title="All India Month-wise Installations")
fig_month.update_traces(textposition="outside")
fig_month.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_month.show()

In [60]:
speed_pattern = df.groupby(["SPEED (Mbps)"])["ACCOUNT NO"].count().reset_index()
speed_pattern.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_speed = px.bar(speed_pattern, x="SPEED (Mbps)", y="No. of Installations",
                   title="All India Speed-wise Installation Count", text="No. of Installations")
fig_speed.update_traces(textposition="outside")
fig_speed.update_layout(bargap=0.2, height=600,
                        xaxis=dict(dtick=50, range=[0,500]))
fig_speed.show()

In [61]:
exec_name = "GANESH KANSE"   # change as needed
exec_data = df[df["SALES EXEC NAME"] == exec_name]

# Speed distribution pie chart
speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
fig_exec_speed.update_traces(textinfo="label+percent")
fig_exec_speed.show()

# Month-wise installations + value
exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
exec_month = exec_month.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                      text="Value", title=f"{exec_name} Month-wise Performance")
fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_exec_bar.update_traces(textposition="outside")
fig_exec_bar.show()

In [62]:
# Executive Performance (if selected)
if execu != "All":
    exec_name, exec_city = execu.split(" (")
    exec_city = exec_city.strip(")")
    exec_data = df[(df["SALES EXEC NAME"] == exec_name) & (df["City"] == exec_city)]

    # Speed distribution pie chart
    speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
    speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

    fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                            title=f"{exec_name} Speed Distribution (Year)")
    fig_exec_speed.update_traces(textinfo="label+percent")  # speeds + %
    st.plotly_chart(fig_exec_speed)

    # Month-wise installations + value
    exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
        {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
    exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
    exec_month = exec_month.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

    fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                          text="Value", title=f"{exec_name} Month-wise Performance")
    fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
    fig_exec_bar.update_traces(textposition="outside")
    st.plotly_chart(fig_exec_bar)

In [63]:
# All India Speed-wise Installation
speed_pattern = df.groupby(["SPEED (Mbps)"])["ACCOUNT NO"].count().reset_index()
speed_pattern.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_speed = px.bar(speed_pattern, x="SPEED (Mbps)", y="No. of Installations",
                   title="All India Speed-wise Installation Count", text="No. of Installations")
fig_speed.update_traces(textposition="outside")
fig_speed.update_layout(bargap=0.2, height=600,
                        xaxis=dict(dtick=50, range=[0,500]))
st.plotly_chart(fig_speed)

# All India Month-wise Installations + Value
month_trend = df.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
month_trend.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
month_trend = month_trend.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_month = px.bar(month_trend, x="MonthYear", y="No. of Installations", text="Value",
                   title="All India Month-wise Installations")
fig_month.update_traces(textposition="outside")
fig_month.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
st.plotly_chart(fig_month)

# SLA Distribution with %
sla_chart = df.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
sla_chart.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)
sla_chart["Percent"] = (sla_chart["No. of Installations"] /
                        sla_chart["No. of Installations"].sum() * 100).round(1)

fig_sla = px.bar(sla_chart, x="SLA_Category", y="No. of Installations",
                 text=sla_chart.apply(lambda row: f"{row['No. of Installations']} ({row['Percent']}%)", axis=1),
                 title="All India SLA Distribution")
fig_sla.update_traces(textposition="outside")
st.plotly_chart(fig_sla)

2026-07-28 19:45:58.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.513 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:45:58.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [64]:
fig.show()

In [65]:
import pandas as pd
import plotly.express as px

# Load corrected dataset
df = pd.read_csv("Registration Report.csv")

print(df.shape)
print(df.columns)
df.head()

(14033, 14)
Index(['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO',
       'CURRENT STATUS', 'SALES EXEC NAME', 'SALES MANGER NAME', 'DEPARTMENT',
       'INSTALLATION NODE', 'NETWORK TYPE', 'REGISTRATION PLAN', 'Plan Value',
       'SPEED (Mbps)', 'VALIDITY In Months'],
      dtype='str')

,City,CREATION DATE,INSTALLATION DATE,ACCOUNT NO,CURRENT STATUS,SALES EXEC NAME,SALES MANGER NAME,DEPARTMENT,INSTALLATION NODE,NETWORK TYPE,REGISTRATION PLAN,Plan Value,SPEED (Mbps),VALIDITY In Months
0,VADODARA,27-06-2025,01-07-2025,2286083,ACTIVE,BHAVITABEN THAKKAR,RAJIV BHATIYA,Sales Direct,G-KARMAJ-02-07C01VA14,GPON,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3
1,PUNE,28-06-2025,01-07-2025,2285899,SUSPEND,Online Sales,Manish Sarode,Online Sales,SW-EVES,MEN,13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...,1076,60,3
2,PUNE,28-06-2025,01-07-2025,2286084,SUSPEND,JAVED SHAIKH,Manish Sarode,TECH SUPPORT,SW-KMALHAR,MEN,12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...,4572,125,6
3,PUNE,28-06-2025,01-07-2025,2286085,SUSPEND,SUGRIV JOGDAND,Manish Sarode,TECH SUPPORT,G-LMD-02-02C01PE29,GPON,13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...,2913,200,3
4,VADODARA,28-06-2025,01-07-2025,2286092,SUSPEND,RAHILKHA SOLANKI,RAJIV BHATIYA,TECH SUPPORT,MAHEFUJ-VADCARD07,HFC,12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...,1500,60,3

In [66]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Month-Year based on Installation Date
df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

In [67]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")

# Month-Year based on Installation Date
df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

In [68]:
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

In [69]:
sla_chart = df.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
sla_chart.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)
sla_chart["Percent"] = (sla_chart["No. of Installations"] /
                        sla_chart["No. of Installations"].sum() * 100).round(1)

fig_sla = px.bar(sla_chart, x="SLA_Category", y="No. of Installations",
                 text=sla_chart.apply(lambda row: f"{row['No. of Installations']} ({row['Percent']}%)", axis=1),
                 title="All India SLA Distribution")
fig_sla.update_traces(textposition="outside")
fig_sla.show()

In [70]:
month_trend = df.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
month_trend.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
month_trend = month_trend.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_month = px.bar(month_trend, x="MonthYear", y="No. of Installations", text="Value",
                   title="All India Month-wise Installations")
fig_month.update_traces(textposition="outside")
fig_month.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_month.show()

In [71]:
speed_pattern = df.groupby(["SPEED (Mbps)"])["ACCOUNT NO"].count().reset_index()
speed_pattern.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_speed = px.bar(speed_pattern, x="SPEED (Mbps)", y="No. of Installations",
                   title="All India Speed-wise Installation Count", text="No. of Installations")
fig_speed.update_traces(textposition="outside")
fig_speed.update_layout(bargap=0.2, height=600,
                        xaxis=dict(dtick=50, range=[0,500]))
fig_speed.show()

In [72]:
exec_name = "GANESH KANSE"   # change as needed
exec_data = df[df["SALES EXEC NAME"] == exec_name]

# Speed distribution pie chart
speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                        title=f"{exec_name} Speed Distribution (Year)")
fig_exec_speed.update_traces(textinfo="label+percent")  # speeds + %
fig_exec_speed.show()

# Month-wise installations + value
exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
exec_month = exec_month.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                      text="Value", title=f"{exec_name} Month-wise Performance")
fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
fig_exec_bar.update_traces(textposition="outside")
fig_exec_bar.show()

In [73]:
import pandas as pd
import streamlit as st
import plotly.express as px

# --- Load dataset ---
df = pd.read_csv("Registration Report.csv")

# --- Parse dates (use Installation Date for month-year) ---
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")
df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], format="%d-%m-%Y", errors="coerce")
df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")

# --- SLA ageing + SLA_Category ---
df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

def sla_bucket(x):
    if pd.isna(x):
        return "Missing"
    elif x <= 2:
        return "0-2 days"
    elif x <= 5:
        return "2-5 days"
    elif x <= 7:
        return "5-7 days"
    else:
        return "Above 7 days"

df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Sidebar Filters ---
st.sidebar.header("Filters")
execu = st.sidebar.selectbox("Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))
month = st.sidebar.selectbox("Month", ["All"] + sorted(df["MonthYear"].dropna().unique(),
                                                      key=lambda x: pd.to_datetime(x, format="%b-%Y")))

# --- SLA Distribution with % ---
sla_chart = df.groupby("SLA_Category")["ACCOUNT NO"].count().reset_index()
sla_chart.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)
sla_chart["Percent"] = (sla_chart["No. of Installations"] /
                        sla_chart["No. of Installations"].sum() * 100).round(1)

fig_sla = px.bar(sla_chart, x="SLA_Category", y="No. of Installations",
                 text=sla_chart.apply(lambda row: f"{row['No. of Installations']} ({row['Percent']}%)", axis=1),
                 title="All India SLA Distribution")
fig_sla.update_traces(textposition="outside")
st.plotly_chart(fig_sla)

# --- All India Month-wise Installations + Value ---
month_trend = df.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
    {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
month_trend.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
month_trend = month_trend.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

fig_month = px.bar(month_trend, x="MonthYear", y="No. of Installations", text="Value",
                   title="All India Month-wise Installations")
fig_month.update_traces(textposition="outside")
fig_month.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
st.plotly_chart(fig_month)

# --- All India Speed-wise Installation ---
speed_pattern = df.groupby(["SPEED (Mbps)"])["ACCOUNT NO"].count().reset_index()
speed_pattern.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

fig_speed = px.bar(speed_pattern, x="SPEED (Mbps)", y="No. of Installations",
                   title="All India Speed-wise Installation Count", text="No. of Installations")
fig_speed.update_traces(textposition="outside")
fig_speed.update_layout(bargap=0.2, height=600,
                        xaxis=dict(dtick=50, range=[0,500]))
st.plotly_chart(fig_speed)

# --- Executive Performance (if selected) ---
if execu != "All":
    exec_data = df[df["SALES EXEC NAME"] == execu]

    # Speed distribution pie chart
    speed_dist = exec_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
    speed_dist.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

    fig_exec_speed = px.pie(speed_dist, names="SPEED (Mbps)", values="No. of Installations",
                            title=f"{execu} Speed Distribution (Year)")
    fig_exec_speed.update_traces(textinfo="label+percent")
    st.plotly_chart(fig_exec_speed)

    # Month-wise installations + value
    exec_month = exec_data.groupby("MonthYear")[["ACCOUNT NO","Plan Value"]].agg(
        {"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index()
    exec_month.rename(columns={"ACCOUNT NO":"No. of Installations","Plan Value":"Value"}, inplace=True)
    exec_month = exec_month.sort_values(by="MonthYear", key=lambda x: pd.to_datetime(x, format="%b-%Y"))

    fig_exec_bar = px.bar(exec_month, x="MonthYear", y="No. of Installations",
                          text="Value", title=f"{execu} Month-wise Performance")
    fig_exec_bar.update_layout(xaxis_title="Year", yaxis_title="No. of Installations")
    fig_exec_bar.update_traces(textposition="outside")
    st.plotly_chart(fig_exec_bar)

# --- Month Performance (if selected) ---
if month != "All":
    month_data = df[df["MonthYear"] == month]
    speed_dist_month = month_data.groupby("SPEED (Mbps)")["ACCOUNT NO"].count().reset_index()
    speed_dist_month.rename(columns={"ACCOUNT NO":"No. of Installations"}, inplace=True)

    fig_month_speed = px.pie(speed_dist_month, names="SPEED (Mbps)", values="No. of Installations",
                             title=f"Speed Distribution for {month}")
    fig_month_speed.update_traces(textinfo="label+percent")
    st.plotly_chart(fig_month_speed)

2026-07-28 19:54:50.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.563 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.667 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 19:54:50.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [74]:
st.sidebar.header("Filters")
execu = st.sidebar.selectbox("Executive", ["All"] + sorted(df["SALES EXEC NAME"].dropna().unique()))
month = st.sidebar.selectbox("Month", ["All"] + sorted(df["MonthYear"].dropna().unique(),
                                                      key=lambda x: pd.to_datetime(x, format="%b-%Y")))

2026-07-28 20:01:41.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-28 20:01:41.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [1]:
import os
print(os.path.exists(os.path.join(os.path.dirname(__file__), "company_logo.png")))

NameError: name '__file__' is not defined

In [2]:
import pandas as pd
import streamlit as st
import plotly.express as px

# --- Load and preprocess data ---
df = pd.read_csv("New Registration Report.csv")   # ✅ updated file name

# Strip stray spaces from headers
df.columns = df.columns.str.strip()

# Parse CREATION DATE safely
if "CREATION DATE" in df.columns:
    df["CREATION DATE"] = pd.to_datetime(
        df["CREATION DATE"],
        dayfirst=True,
        errors="coerce"
    )

# Parse INSTALLATION DATE safely
if "INSTALLATION DATE" in df.columns:
    df["INSTALLATION DATE"] = pd.to_datetime(
        df["INSTALLATION DATE"],
        dayfirst=True,
        errors="coerce"
    )
    # Derive MonthYear and Year
    df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")
    df["Year"] = df["INSTALLATION DATE"].dt.year

# SLA ageing calculation
if "CREATION DATE" in df.columns and "INSTALLATION DATE" in df.columns:
    df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

    def sla_bucket(x):
        if pd.isna(x):
            return "Missing"
        elif x <= 2:
            return "0-2 days"
        elif x <= 5:
            return "2-5 days"
        elif x <= 7:
            return "5-7 days"
        else:
            return "Above 7 days"

    df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# Ensure Plan Value exists
if "Plan Value" not in df.columns:
    raise KeyError("Expected column 'Plan Value' not found in dataset")
df["Plan Value"] = df["Plan Value"].fillna(0)

In [3]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("New Registration Report.csv")   # ✅ updated file name

# --- Clean headers ---
df.columns = df.columns.str.strip()

# --- Parse dates ---
if "CREATION DATE" in df.columns:
    df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], dayfirst=True, errors="coerce")

if "INSTALLATION DATE" in df.columns:
    df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], dayfirst=True, errors="coerce")
    # Derive MonthYear and Year
    df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")
    df["Year"] = df["INSTALLATION DATE"].dt.year

# --- SLA ageing ---
if "CREATION DATE" in df.columns and "INSTALLATION DATE" in df.columns:
    df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

    def sla_bucket(x):
        if pd.isna(x):
            return "Missing"
        elif x <= 2:
            return "0-2 days"
        elif x <= 5:
            return "2-5 days"
        elif x <= 7:
            return "5-7 days"
        else:
            return "Above 7 days"

    df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Ensure Plan Value exists ---
if "Plan Value" not in df.columns:
    raise KeyError("Expected column 'Plan Value' not found in dataset")
df["Plan Value"] = df["Plan Value"].fillna(0)

In [4]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("New Registration Report.csv")   # ✅ updated file name

# --- Clean headers ---
df.columns = df.columns.str.strip()

# --- Parse dates ---
if "CREATION DATE" in df.columns:
    df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], dayfirst=True, errors="coerce")

if "INSTALLATION DATE" in df.columns:
    df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], dayfirst=True, errors="coerce")
    # Derive MonthYear and Year
    df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")
    df["Year"] = df["INSTALLATION DATE"].dt.year

# --- SLA ageing ---
if "CREATION DATE" in df.columns and "INSTALLATION DATE" in df.columns:
    df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

    def sla_bucket(x):
        if pd.isna(x):
            return "Missing"
        elif x <= 2:
            return "0-2 days"
        elif x <= 5:
            return "2-5 days"
        elif x <= 7:
            return "5-7 days"
        else:
            return "Above 7 days"

    df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Ensure Plan Value exists ---
if "Plan Value" not in df.columns:
    raise KeyError("Expected column 'Plan Value' not found in dataset")
df["Plan Value"] = df["Plan Value"].fillna(0)

# --- Quick validation ---
print("Columns:", df.columns.tolist())
print(df.head())

Columns: ['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO', 'ADDRESS', 'CUSTOMER CURRENT STATUS', 'SALES EXEC NAME', 'SALES CODE', 'SALES EXEC DOJ', 'SALES EXEC STATUS', 'SALES TL NAME', 'SALES MANGER NAME', 'DEPARTMENT', 'INSTALLATION NODE', 'NETWORK TYPE', 'INSTALLATION ENGINEER NAME', 'REGISTRATION PLAN', 'Plan Value', 'SPEED (Mbps)', 'VALIDITY In Months', 'ARPU', 'ARPU SLAB', 'MonthYear', 'Year', 'TAT_days', 'SLA_Category']
       City CREATION DATE INSTALLATION DATE  ACCOUNT NO  \
0  VADODARA    2025-06-27        2025-07-01     2286083
1      PUNE    2025-06-28        2025-07-01     2285899
2      PUNE    2025-06-28        2025-07-01     2286084
3      PUNE    2025-06-28        2025-07-01     2286085
4  VADODARA    2025-06-28        2025-07-01     2286092

                                             ADDRESS CUSTOMER CURRENT STATUS  \
0  C 405,, SHARNAM RESIDENCY,, OPP RUDRARAJ DUP,,...                  ACTIVE
1  FLAT NO 2,, SAMARTH APARTMENT,, VIDATE VASTE L...                 SUSPEND
2  SH NO 4,, YASHODHANPRIME PANACHA,, BANER,, BAN...                 SUSPEND
3  101,, SAGAR CO OP SOC PL NO 02,, GROUND FLOOR,...                 SUSPEND
4                                                NaN                 SUSPEND

      SALES EXEC NAME SALES CODE SALES EXEC DOJ SALES EXEC STATUS  ...  \
0  BHAVITABEN THAKKAR    VA10108            NaN          Inactive  ...
1        Online Sales    VA05001            NaN            Active  ...
2        JAVED SHAIKH    PW06530            NaN            Active  ...
3      SUGRIV JOGDAND    PW06372            NaN            Active  ...
4    RAHILKHA SOLANKI    VA10080            NaN            Active  ...

                                   REGISTRATION PLAN Plan Value SPEED (Mbps)  \
0  12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...       1500           60
1  13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...       1076           60
2  12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...       4572          125
3  13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...       2913          200
4  12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...       1500           60

  VALIDITY In Months ARPU ARPU SLAB MonthYear  Year  TAT_days  SLA_Category
0                  3  500   301-500  Jul-2025  2025         4      2-5 days
1                  3  359   301-500  Jul-2025  2025         3      2-5 days
2                  6  762      751+  Jul-2025  2025         3      2-5 days
3                  3  971      751+  Jul-2025  2025         3      2-5 days
4                  3  500   301-500  Jul-2025  2025         3      2-5 days

[5 rows x 26 columns]

In [5]:
import pandas as pd

# --- Load dataset ---
df = pd.read_csv("New Registration Report.csv")   # ✅ updated file name

# --- Clean headers ---
df.columns = df.columns.str.strip()

# --- Parse dates ---
if "CREATION DATE" in df.columns:
    df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], dayfirst=True, errors="coerce")

if "INSTALLATION DATE" in df.columns:
    df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], dayfirst=True, errors="coerce")
    # Derive MonthYear and Year
    df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")
    df["Year"] = df["INSTALLATION DATE"].dt.year

# --- SLA ageing ---
if "CREATION DATE" in df.columns and "INSTALLATION DATE" in df.columns:
    df["TAT_days"] = (df["INSTALLATION DATE"] - df["CREATION DATE"]).dt.days

    def sla_bucket(x):
        if pd.isna(x):
            return "Missing"
        elif x <= 2:
            return "0-2 days"
        elif x <= 5:
            return "2-5 days"
        elif x <= 7:
            return "5-7 days"
        else:
            return "Above 7 days"

    df["SLA_Category"] = df["TAT_days"].apply(sla_bucket)

# --- Ensure Plan Value exists ---
if "Plan Value" not in df.columns:
    raise KeyError("Expected column 'Plan Value' not found in dataset")
df["Plan Value"] = df["Plan Value"].fillna(0)

# --- Quick validation ---
print("Columns:", df.columns.tolist())
print(df.head())

Columns: ['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO', 'ADDRESS', 'CUSTOMER CURRENT STATUS', 'SALES EXEC NAME', 'SALES CODE', 'SALES EXEC DOJ', 'SALES EXEC STATUS', 'SALES TL NAME', 'SALES MANGER NAME', 'DEPARTMENT', 'INSTALLATION NODE', 'NETWORK TYPE', 'INSTALLATION ENGINEER NAME', 'REGISTRATION PLAN', 'Plan Value', 'SPEED (Mbps)', 'VALIDITY In Months', 'ARPU', 'ARPU SLAB', 'MonthYear', 'Year', 'TAT_days', 'SLA_Category']
       City CREATION DATE INSTALLATION DATE  ACCOUNT NO  \
0  VADODARA    2025-06-27        2025-07-01     2286083
1      PUNE    2025-06-28        2025-07-01     2285899
2      PUNE    2025-06-28        2025-07-01     2286084
3      PUNE    2025-06-28        2025-07-01     2286085
4  VADODARA    2025-06-28        2025-07-01     2286092

                                             ADDRESS CUSTOMER CURRENT STATUS  \
0  C 405,, SHARNAM RESIDENCY,, OPP RUDRARAJ DUP,,...                  ACTIVE
1  FLAT NO 2,, SAMARTH APARTMENT,, VIDATE VASTE L...                 SUSPEND
2  SH NO 4,, YASHODHANPRIME PANACHA,, BANER,, BAN...                 SUSPEND
3  101,, SAGAR CO OP SOC PL NO 02,, GROUND FLOOR,...                 SUSPEND
4                                                NaN                 SUSPEND

      SALES EXEC NAME SALES CODE SALES EXEC DOJ SALES EXEC STATUS  ...  \
0  BHAVITABEN THAKKAR    VA10108            NaN          Inactive  ...
1        Online Sales    VA05001            NaN            Active  ...
2        JAVED SHAIKH    PW06530            NaN            Active  ...
3      SUGRIV JOGDAND    PW06372            NaN            Active  ...
4    RAHILKHA SOLANKI    VA10080            NaN            Active  ...

                                   REGISTRATION PLAN Plan Value SPEED (Mbps)  \
0  12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...       1500           60
1  13366/YOU UNLTD 60 Mbps/60Mbps-2Mbps/10.5TB/3M...       1076           60
2  12934/YOU UNLTD 125 Mbps/125Mbps-2Mbps/21TB/6M...       4572          125
3  13002/YOU UNLTD 200 Mbps/200Mbps-2Mbps/10.5TB/...       2913          200
4  12791/YOU UNLTD 60 Mbps/60Mbps-1Mbps/10.5TB/3M...       1500           60

  VALIDITY In Months ARPU ARPU SLAB MonthYear  Year  TAT_days  SLA_Category
0                  3  500   301-500  Jul-2025  2025         4      2-5 days
1                  3  359   301-500  Jul-2025  2025         3      2-5 days
2                  6  762      751+  Jul-2025  2025         3      2-5 days
3                  3  971      751+  Jul-2025  2025         3      2-5 days
4                  3  500   301-500  Jul-2025  2025         3      2-5 days

[5 rows x 26 columns]

In [6]:
# --- Quick sanity check summary ---

print("✅ Dataset loaded successfully")
print(f"Total rows: {len(df)}")
print(f"Columns: {df.columns.tolist()}")

# Total installations
if "ACCOUNT NO" in df.columns:
    total_installs = df["ACCOUNT NO"].count()
    print(f"Total Installations: {total_installs}")

# Total value
if "Plan Value" in df.columns:
    total_value = df["Plan Value"].sum()
    print(f"Total Plan Value: ₹{total_value:,.0f}")

# SLA distribution
if "SLA_Category" in df.columns:
    print("\nSLA Distribution:")
    print(df["SLA_Category"].value_counts())

# Average metrics
if "Plan Value" in df.columns:
    print(f"\nAverage Plan Value: ₹{df['Plan Value'].mean():,.0f}")
if "TAT_days" in df.columns:
    print(f"Average TAT (days): {df['TAT_days'].mean():.2f}")

✅ Dataset loaded successfully
Total rows: 14033
Columns: ['City', 'CREATION DATE', 'INSTALLATION DATE', 'ACCOUNT NO', 'ADDRESS', 'CUSTOMER CURRENT STATUS', 'SALES EXEC NAME', 'SALES CODE', 'SALES EXEC DOJ', 'SALES EXEC STATUS', 'SALES TL NAME', 'SALES MANGER NAME', 'DEPARTMENT', 'INSTALLATION NODE', 'NETWORK TYPE', 'INSTALLATION ENGINEER NAME', 'REGISTRATION PLAN', 'Plan Value', 'SPEED (Mbps)', 'VALIDITY In Months', 'ARPU', 'ARPU SLAB', 'MonthYear', 'Year', 'TAT_days', 'SLA_Category']
Total Installations: 14033
Total Plan Value: ₹41,218,154

SLA Distribution:
SLA_Category
0-2 days        7516
2-5 days        4153
Above 7 days    1277
5-7 days        1087
Name: count, dtype: int64

Average Plan Value: ₹2,937
Average TAT (days): 3.56

In [1]:
# --- Date Parsing ---
if "CREATION DATE" in df.columns:
    df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], dayfirst=True, errors="coerce")

if "INSTALLATION DATE" in df.columns:
    df["INSTALLATION DATE"] = pd.to_datetime(df["INSTALLATION DATE"], dayfirst=True, errors="coerce")
    df["MonthYear"] = df["INSTALLATION DATE"].dt.strftime("%b-%Y")
    df["Year"] = df["INSTALLATION DATE"].dt.year

NameError: name 'df' is not defined

In [2]:
df["CREATION DATE"] = pd.to_datetime(df["CREATION DATE"], format="%d-%m-%Y", errors="coerce")

NameError: name 'pd' is not defined

In [1]:
# --- Executive Summary Generator Testing Notebook ---

import pandas as pd

# Universal formatter
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# Enhanced summary generator
def generate_summary(df, level="Month", group_col=None, value_col=None, install_col=None):
    summary = ""

    if level == "Month":
        last = df.iloc[-1]
        prev = df.iloc[-2] if len(df) > 1 else None
        if prev is not None:
            change_installs = last[install_col] - prev[install_col]
            change_value = last[value_col] - prev[value_col]

            pct_installs = (change_installs / prev[install_col] * 100) if prev[install_col] != 0 else 0
            pct_value = (change_value / prev[value_col] * 100) if prev[value_col] != 0 else 0

            summary = (
                f"In {last['MonthYear']}, installs were {last[install_col]} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last[value_col])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%)."
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last[install_col]} installs and ₹{format_value(last[value_col])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"sum"),
            Value=(value_col,"sum")
        ).reset_index()

        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

In [2]:
# --- Executive Summary Generator (Final Version) ---

import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# Universal formatter
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# Enhanced summary generator
def generate_summary(df, level="Month", group_col=None, value_col="Plan Value", install_col="ACCOUNT NO"):
    summary = ""

    if level == "Month":
        # Aggregate by MonthYear
        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            summary = (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%)."
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        # Top 3 performers
        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

In [3]:
import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# --- Universal Formatter ---
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# --- Trendline Streak Detector ---
def detect_streak(series, label="installs"):
    streak = 0
    direction = None
    for i in range(1, len(series)):
        if series[i] > series[i-1]:
            if direction == "up":
                streak += 1
            else:
                direction = "up"
                streak = 1
        elif series[i] < series[i-1]:
            if direction == "down":
                streak += 1
            else:
                direction = "down"
                streak = 1
    if streak >= 2:
        return f"{label.capitalize()} have {direction} for {streak} consecutive periods."
    return ""

# --- Enhanced Summary Generator ---
def generate_summary(df, level="Month", group_col=None, value_col="Plan Value", install_col="ACCOUNT NO"):
    summary = ""

    if level == "Month":
        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            streak_msg = detect_streak(grouped["Installs"].tolist(), "installs")
            streak_val_msg = detect_streak(grouped["Value"].tolist(), "value")

            summary = (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%). "
                f"{streak_msg} {streak_val_msg}"
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

In [4]:
# Month-level summary
print(generate_summary(new_reg_df, level="Month"))

# City-level summary
print(generate_summary(new_reg_df, level="City", group_col="City"))

# Executive-level summary
print(generate_summary(new_reg_df, level="Executive", group_col="Executive"))

# Node-level summary
print(generate_summary(new_reg_df, level="Node", group_col="Node"))

# Plan Validity summary
print(generate_summary(new_reg_df, level="PlanValidity", group_col="Validity"))

# Speed-level summary
print(generate_summary(new_reg_df, level="Speed", group_col="Speed (Mbps)"))

KeyError: 'MonthYear'

In [5]:
# Ensure date column is parsed
new_reg_df["Registration Date"] = pd.to_datetime(new_reg_df["Registration Date"], errors="coerce")

# Create MonthYear string (e.g., "Jun-2026")
new_reg_df["MonthYear"] = new_reg_df["Registration Date"].dt.strftime("%b-%Y")

KeyError: 'Registration Date'

In [6]:
import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# --- Universal Formatter ---
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# --- Trendline Streak Detector ---
def detect_streak(series, label="installs"):
    streak = 0
    direction = None
    for i in range(1, len(series)):
        if series[i] > series[i-1]:
            if direction == "up":
                streak += 1
            else:
                direction = "up"
                streak = 1
        elif series[i] < series[i-1]:
            if direction == "down":
                streak += 1
            else:
                direction = "down"
                streak = 1
    if streak >= 2:
        return f"{label.capitalize()} have {direction} for {streak} consecutive periods."
    return ""

# --- Enhanced Summary Generator ---
def generate_summary(df, level="Month", group_col=None, value_col="Plan Value", install_col="ACCOUNT NO"):
    summary = ""

    # Auto-create MonthYear if missing
    if "MonthYear" not in df.columns and "Registration Date" in df.columns:
        df["Registration Date"] = pd.to_datetime(df["Registration Date"], errors="coerce")
        df["MonthYear"] = df["Registration Date"].dt.strftime("%b-%Y")

    if level == "Month":
        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            streak_msg = detect_streak(grouped["Installs"].tolist(), "installs")
            streak_val_msg = detect_streak(grouped["Value"].tolist(), "value")

            summary = (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%). "
                f"{streak_msg} {streak_val_msg}"
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        )..reset_index()

        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

SyntaxError: invalid syntax (3805898774.py, line 78)

In [7]:
import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# --- Universal Formatter ---
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# --- Trendline Streak Detector ---
def detect_streak(series, label="installs"):
    streak = 0
    direction = None
    for i in range(1, len(series)):
        if series[i] > series[i-1]:
            if direction == "up":
                streak += 1
            else:
                direction = "up"
                streak = 1
        elif series[i] < series[i-1]:
            if direction == "down":
                streak += 1
            else:
                direction = "down"
                streak = 1
    if streak >= 2:
        return f"{label.capitalize()} have {direction} for {streak} consecutive periods."
    return ""

# --- Enhanced Summary Generator ---
def generate_summary(df, level="Month", group_col=None, value_col="Plan Value", install_col="ACCOUNT NO"):
    summary = ""

    # Auto-create MonthYear if missing
    if "MonthYear" not in df.columns and "Registration Date" in df.columns:
        df["Registration Date"] = pd.to_datetime(df["Registration Date"], errors="coerce")
        df["MonthYear"] = df["Registration Date"].dt.strftime("%b-%Y")

    if level == "Month":
        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            streak_msg = detect_streak(grouped["Installs"].tolist(), "installs")
            streak_val_msg = detect_streak(grouped["Value"].tolist(), "value")

            summary = (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%). "
                f"{streak_msg} {streak_val_msg}"
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

In [8]:
print(generate_summary(new_reg_df, level="Month"))
print(generate_summary(new_reg_df, level="City", group_col="City"))
print(generate_summary(new_reg_df, level="Executive", group_col="Executive"))
print(generate_summary(new_reg_df, level="Node", group_col="Node"))
print(generate_summary(new_reg_df, level="PlanValidity", group_col="Validity"))
print(generate_summary(new_reg_df, level="Speed", group_col="Speed (Mbps)"))

KeyError: 'MonthYear'

In [9]:
import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# --- Universal Formatter ---
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# --- Trendline Streak Detector ---
def detect_streak(series, label="installs"):
    streak = 0
    direction = None
    for i in range(1, len(series)):
        if series[i] > series[i-1]:
            if direction == "up":
                streak += 1
            else:
                direction = "up"
                streak = 1
        elif series[i] < series[i-1]:
            if direction == "down":
                streak += 1
            else:
                direction = "down"
                streak = 1
    if streak >= 2:
        return f"{label.capitalize()} have {direction} for {streak} consecutive periods."
    return ""

# --- Enhanced Summary Generator ---
def generate_summary(df, level="Month", group_col=None, value_col="Plan Value", install_col="ACCOUNT NO"):
    summary = ""

    # Auto-create MonthYear if missing
    if level == "Month":
        if "MonthYear" not in df.columns:
            # Try to detect a date column
            date_col = None
            for col in df.columns:
                if "date" in col.lower():
                    date_col = col
                    break
            if date_col:
                df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
                df["MonthYear"] = df[date_col].dt.strftime("%b-%Y")
            else:
                raise KeyError("No date column found to create MonthYear")

        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            streak_msg = detect_streak(grouped["Installs"].tolist(), "installs")
            streak_val_msg = detect_streak(grouped["Value"].tolist(), "value")

            summary = (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%). "
                f"{streak_msg} {streak_val_msg}"
            )
        else:
            summary = f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level in ["City","Executive","Node","PlanValidity","Speed"]:
        grouped = df.groupby(group_col).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        top3 = grouped.sort_values("Installs",ascending=False).head(3)
        top_summary = "; ".join([
            f"{row[group_col]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
            for _, row in top3.iterrows()
        ])

        bottom = grouped.sort_values("Installs",ascending=True).iloc[0]

        total_installs = grouped["Installs"].sum()
        total_value = grouped["Value"].sum()

        summary = (
            f"Top 3 {level}s by installs: {top_summary}. "
            f"Lowest {level}: {bottom[group_col]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
            f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
        )

    return summary

In [10]:
import pandas as pd

# Load your New Registration Report
new_reg_df = pd.read_csv("New Registration Report.csv")

# --- Universal Formatter ---
def format_value(num):
    if num >= 1_000_000:
        return f"{num/1_000_000:.1f} M"
    elif num >= 100_000:
        return f"{num/100_000:.1f} L"
    else:
        return f"{round(num):,}"

# --- Column Mapping Helper ---
def map_columns(df):
    col_map = {}
    for col in df.columns:
        low = col.lower()
        if "account" in low or "acct" in low:
            col_map["install_col"] = col
        elif "plan" in low and "val" in low:
            col_map["value_col"] = col
        elif "exec" in low:
            col_map["exec_col"] = col
        elif "city" in low:
            col_map["city_col"] = col
        elif "node" in low:
            col_map["node_col"] = col
        elif "valid" in low:
            col_map["validity_col"] = col
        elif "speed" in low:
            col_map["speed_col"] = col
        elif "date" in low:
            col_map["date_col"] = col
    return col_map

# --- Trendline Streak Detector ---
def detect_streak(series, label="installs"):
    streak = 0
    direction = None
    for i in range(1, len(series)):
        if series[i] > series[i-1]:
            if direction == "up":
                streak += 1
            else:
                direction = "up"
                streak = 1
        elif series[i] < series[i-1]:
            if direction == "down":
                streak += 1
            else:
                direction = "down"
                streak = 1
    if streak >= 2:
        return f"{label.capitalize()} have {direction} for {streak} consecutive periods."
    return ""

# --- Enhanced Summary Generator ---
def generate_summary(df, level="Month"):
    cols = map_columns(df)
    install_col = cols.get("install_col")
    value_col = cols.get("value_col")

    # Auto-create MonthYear if missing
    if level == "Month":
        if "MonthYear" not in df.columns:
            if "date_col" in cols:
                df[cols["date_col"]] = pd.to_datetime(df[cols["date_col"]], errors="coerce")
                df["MonthYear"] = df[cols["date_col"]].dt.strftime("%b-%Y")
            else:
                raise KeyError("No date column found to create MonthYear")

        grouped = df.groupby("MonthYear").agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

        last = grouped.iloc[-1]
        prev = grouped.iloc[-2] if len(grouped) > 1 else None

        if prev is not None:
            change_installs = last["Installs"] - prev["Installs"]
            change_value = last["Value"] - prev["Value"]

            pct_installs = (change_installs / prev["Installs"] * 100) if prev["Installs"] != 0 else 0
            pct_value = (change_value / prev["Value"] * 100) if prev["Value"] != 0 else 0

            streak_msg = detect_streak(grouped["Installs"].tolist(), "installs")
            streak_val_msg = detect_streak(grouped["Value"].tolist(), "value")

            return (
                f"In {last['MonthYear']}, installs were {last['Installs']} "
                f"({change_installs:+}, {pct_installs:+.1f}% vs {prev['MonthYear']}), "
                f"and value was ₹{format_value(last['Value'])} "
                f"({format_value(change_value)} change, {pct_value:+.1f}%). "
                f"{streak_msg} {streak_val_msg}"
            )
        else:
            return f"Initial month {last['MonthYear']} shows {last['Installs']} installs and ₹{format_value(last['Value'])} value."

    elif level == "City":
        grouped = df.groupby(cols["city_col"]).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

    elif level == "Executive":
        grouped = df.groupby(cols["exec_col"]).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

    elif level == "Node":
        grouped = df.groupby(cols["node_col"]).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

    elif level == "PlanValidity":
        grouped = df.groupby(cols["validity_col"]).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

    elif level == "Speed":
        grouped = df.groupby(cols["speed_col"]).agg(
            Installs=(install_col,"count"),
            Value=(value_col,"sum")
        ).reset_index()

    # Top 3 + lowest summary
    top3 = grouped.sort_values("Installs",ascending=False).head(3)
    top_summary = "; ".join([
        f"{row.iloc[0]} ({row['Installs']} installs, ₹{format_value(row['Value'])})"
        for _, row in top3.iterrows()
    ])
    bottom = grouped.sort_values("Installs",ascending=True).iloc[0]
    total_installs = grouped["Installs"].sum()
    total_value = grouped["Value"].sum()

    return (
        f"Top 3 {level}s by installs: {top_summary}. "
        f"Lowest {level}: {bottom.iloc[0]} ({bottom['Installs']} installs, ₹{format_value(bottom['Value'])}). "
        f"Overall {level}-level total: {total_installs} installs, ₹{format_value(total_value)}."
    )

In [11]:
print(generate_summary(new_reg_df, level="Month"))
print(generate_summary(new_reg_df, level="City"))
print(generate_summary(new_reg_df, level="Executive"))
print(generate_summary(new_reg_df, level="Node"))
print(generate_summary(new_reg_df, level="PlanValidity"))
print(generate_summary(new_reg_df, level="Speed"))

In Sep-2026, installs were 246 (-43, -14.9% vs Sep-2025), and value was ₹7.4 L (-35,491 change, -4.6%).
Top 3 Citys by installs: SURAT (3915 installs, ₹11.4 M); VADODARA (2864 installs, ₹8.6 M); PUNE (1628 installs, ₹5.2 M). Lowest City: VALSAD (6 installs, ₹25,079). Overall City-level total: 14033 installs, ₹41.2 M.
Top 3 Executives by installs: Active (10363 installs, ₹31.5 M); Inactive (3670 installs, ₹9.7 M). Lowest Executive: Inactive (3670 installs, ₹9.7 M). Overall Executive-level total: 14033 installs, ₹41.2 M.
Top 3 Nodes by installs: SW-AMANORA (148 installs, ₹5.0 L); GOPIPURA-SURCARD04 (90 installs, ₹2.0 L); SIDHARTHSOC-SURCARD04 (70 installs, ₹1.4 L). Lowest Node: ABOLI-PUNECARD03 (1 installs, ₹2,654). Overall Node-level total: 14033 installs, ₹41.2 M.
Top 3 PlanValiditys by installs: 6 (6415 installs, ₹17.2 M); 3 (3950 installs, ₹6.4 M); 12 (3663 installs, ₹17.6 M). Lowest PlanValidity: 1 (5 installs, ₹30,995). Overall PlanValidity-level total: 14033 installs, ₹41.2 M.
Top 3 Speeds by installs: 40 (3422 installs, ₹8.6 M); 30 (2421 installs, ₹6.4 M); 60 (2398 installs, ₹7.3 M). Lowest Speed: 1000 (4 installs, ₹83,988). Overall Speed-level total: 14033 installs, ₹41.2 M.

In [12]:
import streamlit as st
import plotly.express as px

# Assume new_reg_df is already loaded
fig_month = px.bar(
    new_reg_df.groupby("MonthYear").agg({"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index(),
    x="MonthYear", y="ACCOUNT NO", title="Month-wise Installations"
)
st.plotly_chart(fig_month)

# Executive summary under the chart
st.write(generate_summary(new_reg_df, level="Month"))

# City-level chart
fig_city = px.bar(
    new_reg_df.groupby("City").agg({"ACCOUNT NO":"count","Plan Value":"sum"}).reset_index(),
    x="City", y="ACCOUNT NO", title="City-wise Installations"
)
st.plotly_chart(fig_city)

# Executive summary under the chart
st.write(generate_summary(new_reg_df, level="City"))

2026-07-30 20:32:33.850 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:33.859 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:33.862 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.729
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Harshal Thakkar\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-07-30 20:32:34.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.843 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.868 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.875 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-07-30 20:32:34.878 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [13]:
import os
from datetime import datetime

def save_summary(summary_text, level):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"{timestamp} | {level} | {summary_text}\n"
    
    # Append to a log file
    with open("executive_summaries.log", "a", encoding="utf-8") as f:
        f.write(log_line)